//------------------------------------------------------------------------------
// <auto-generated>
//     Esse código foi gerado por uma ferramenta.
//
//     As alterações no arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BarueriWebService
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.barueri.sp.gov.br/nfe", ConfigurationName="BarueriWebService.wsGeraXmlSoap")]
    public interface wsGeraXmlSoap
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.barueri.sp.gov.br/nfe/ConsultaNFeRecebidaPeriodo", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        BarueriWebService.ConsultarNfeResposta ConsultaNFeRecebidaPeriodo(int VersaoSchema, string MensagemXML);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.barueri.sp.gov.br/nfe/ConsultaNFeRecebidaPeriodo", ReplyAction="*")]
        System.Threading.Tasks.Task<BarueriWebService.ConsultarNfeResposta> ConsultaNFeRecebidaPeriodoAsync(int VersaoSchema, string MensagemXML);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.barueri.sp.gov.br/nfe/ConsultaNFeRecebidaCompetencia", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        BarueriWebService.ConsultarNfeResposta ConsultaNFeRecebidaCompetencia(int VersaoSchema, string MensagemXML);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.barueri.sp.gov.br/nfe/ConsultaNFeRecebidaCompetencia", ReplyAction="*")]
        System.Threading.Tasks.Task<BarueriWebService.ConsultarNfeResposta> ConsultaNFeRecebidaCompetenciaAsync(int VersaoSchema, string MensagemXML);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.barueri.sp.gov.br/nfe/ConsultaNFeRecebidaNumero", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        BarueriWebService.ConsultarNfeResposta ConsultaNFeRecebidaNumero(int VersaoSchema, string MensagemXML);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.barueri.sp.gov.br/nfe/ConsultaNFeRecebidaNumero", ReplyAction="*")]
        System.Threading.Tasks.Task<BarueriWebService.ConsultarNfeResposta> ConsultaNFeRecebidaNumeroAsync(int VersaoSchema, string MensagemXML);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.barueri.sp.gov.br/nfe/ConsultaNFeAutencididade", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        BarueriWebService.ConsultarNfeServPrestadoResposta ConsultaNFeAutencididade(string CodigoAutenticidade, string CPFCNPJTomador);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.barueri.sp.gov.br/nfe/ConsultaNFeAutencididade", ReplyAction="*")]
        System.Threading.Tasks.Task<BarueriWebService.ConsultarNfeServPrestadoResposta> ConsultaNFeAutencididadeAsync(string CodigoAutenticidade, string CPFCNPJTomador);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.barueri.sp.gov.br/nfe")]
    public partial class ConsultarNfeResposta
    {
        
        private CompNfe listaNfeField;
        
        private MensagemRetorno[] listaMensagemRetornoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public CompNfe ListaNfe
        {
            get
            {
                return this.listaNfeField;
            }
            set
            {
                this.listaNfeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ListaMensagemRetorno", Order=1)]
        public MensagemRetorno[] ListaMensagemRetorno
        {
            get
            {
                return this.listaMensagemRetornoField;
            }
            set
            {
                this.listaMensagemRetornoField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.barueri.sp.gov.br/nfe")]
    public partial class CompNfe
    {
        
        private Nfe[] compNfe1Field;
        
        private string paginaField;
        
        private string paginasField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("CompNfe", Order=0)]
        public Nfe[] CompNfe1
        {
            get
            {
                return this.compNfe1Field;
            }
            set
            {
                this.compNfe1Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Pagina
        {
            get
            {
                return this.paginaField;
            }
            set
            {
                this.paginaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string Paginas
        {
            get
            {
                return this.paginasField;
            }
            set
            {
                this.paginasField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.barueri.sp.gov.br/nfe")]
    public partial class Nfe
    {
        
        private InfNFe nfe1Field;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Nfe", Order=0)]
        public InfNFe Nfe1
        {
            get
            {
                return this.nfe1Field;
            }
            set
            {
                this.nfe1Field = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.barueri.sp.gov.br/nfe")]
    public partial class InfNFe
    {
        
        private DadosInfNFe infNFe1Field;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("InfNFe", Order=0)]
        public DadosInfNFe InfNFe1
        {
            get
            {
                return this.infNFe1Field;
            }
            set
            {
                this.infNFe1Field = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.barueri.sp.gov.br/nfe")]
    public partial class DadosInfNFe
    {
        
        private int numeroNfeField;
        
        private string codigoVerificacaoField;
        
        private string dataEmissaoField;
        
        private string nfeSubstituidaField;
        
        private ValoresNFe valoresNfeField;
        
        private PrestadorServico prestadorServicoField;
        
        private DeclaracaoPrestacaoServico declaracaoPrestacaoServicoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int NumeroNfe
        {
            get
            {
                return this.numeroNfeField;
            }
            set
            {
                this.numeroNfeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string CodigoVerificacao
        {
            get
            {
                return this.codigoVerificacaoField;
            }
            set
            {
                this.codigoVerificacaoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string DataEmissao
        {
            get
            {
                return this.dataEmissaoField;
            }
            set
            {
                this.dataEmissaoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string NfeSubstituida
        {
            get
            {
                return this.nfeSubstituidaField;
            }
            set
            {
                this.nfeSubstituidaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public ValoresNFe ValoresNfe
        {
            get
            {
                return this.valoresNfeField;
            }
            set
            {
                this.valoresNfeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public PrestadorServico PrestadorServico
        {
            get
            {
                return this.prestadorServicoField;
            }
            set
            {
                this.prestadorServicoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public DeclaracaoPrestacaoServico DeclaracaoPrestacaoServico
        {
            get
            {
                return this.declaracaoPrestacaoServicoField;
            }
            set
            {
                this.declaracaoPrestacaoServicoField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.barueri.sp.gov.br/nfe")]
    public partial class ValoresNFe
    {
        
        private string baseCalculoField;
        
        private string aliquotaField;
        
        private string valorIssField;
        
        private string valorLiquidoNfeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string BaseCalculo
        {
            get
            {
                return this.baseCalculoField;
            }
            set
            {
                this.baseCalculoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Aliquota
        {
            get
            {
                return this.aliquotaField;
            }
            set
            {
                this.aliquotaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string ValorIss
        {
            get
            {
                return this.valorIssField;
            }
            set
            {
                this.valorIssField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string ValorLiquidoNfe
        {
            get
            {
                return this.valorLiquidoNfeField;
            }
            set
            {
                this.valorLiquidoNfeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.barueri.sp.gov.br/nfe")]
    public partial class CancelamentoNFe
    {
        
        private string dataCancelamentoField;
        
        private string motivoCancelamentoField;
        
        private string nfeSubstitutaField;
        
        private string dataEmissaoNfeSubstitutaField;
        
        private string descricaoCancelamentoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string DataCancelamento
        {
            get
            {
                return this.dataCancelamentoField;
            }
            set
            {
                this.dataCancelamentoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string MotivoCancelamento
        {
            get
            {
                return this.motivoCancelamentoField;
            }
            set
            {
                this.motivoCancelamentoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string NfeSubstituta
        {
            get
            {
                return this.nfeSubstitutaField;
            }
            set
            {
                this.nfeSubstitutaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string DataEmissaoNfeSubstituta
        {
            get
            {
                return this.dataEmissaoNfeSubstitutaField;
            }
            set
            {
                this.dataEmissaoNfeSubstitutaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string DescricaoCancelamento
        {
            get
            {
                return this.descricaoCancelamentoField;
            }
            set
            {
                this.descricaoCancelamentoField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.barueri.sp.gov.br/nfe")]
    public partial class DadosCartaCorrecaoNFe
    {
        
        private string dataEmissaoField;
        
        private string especificacaoField;
        
        private string retificacaoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string DataEmissao
        {
            get
            {
                return this.dataEmissaoField;
            }
            set
            {
                this.dataEmissaoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Especificacao
        {
            get
            {
                return this.especificacaoField;
            }
            set
            {
                this.especificacaoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string Retificacao
        {
            get
            {
                return this.retificacaoField;
            }
            set
            {
                this.retificacaoField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.barueri.sp.gov.br/nfe")]
    public partial class Prestador
    {
        
        private IdentificacaoPrestador identificacaoPrestadorField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public IdentificacaoPrestador IdentificacaoPrestador
        {
            get
            {
                return this.identificacaoPrestadorField;
            }
            set
            {
                this.identificacaoPrestadorField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.barueri.sp.gov.br/nfe")]
    public partial class IdentificacaoPrestador
    {
        
        private CpfCnpj cpfCnpjField;
        
        private string inscricaoMunicipalField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public CpfCnpj CpfCnpj
        {
            get
            {
                return this.cpfCnpjField;
            }
            set
            {
                this.cpfCnpjField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string InscricaoMunicipal
        {
            get
            {
                return this.inscricaoMunicipalField;
            }
            set
            {
                this.inscricaoMunicipalField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.barueri.sp.gov.br/nfe")]
    public partial class CpfCnpj
    {
        
        private string cpfField;
        
        private string cnpjField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Cpf
        {
            get
            {
                return this.cpfField;
            }
            set
            {
                this.cpfField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Cnpj
        {
            get
            {
                return this.cnpjField;
            }
            set
            {
                this.cnpjField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.barueri.sp.gov.br/nfe")]
    public partial class Fatura
    {
        
        private string numeroFaturaField;
        
        private string valorFaturaField;
        
        private string formaPagamentoFaturaField;
        
        private string valorExtensoFaturaField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string NumeroFatura
        {
            get
            {
                return this.numeroFaturaField;
            }
            set
            {
                this.numeroFaturaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string ValorFatura
        {
            get
            {
                return this.valorFaturaField;
            }
            set
            {
                this.valorFaturaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string FormaPagamentoFatura
        {
            get
            {
                return this.formaPagamentoFaturaField;
            }
            set
            {
                this.formaPagamentoFaturaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string ValorExtensoFatura
        {
            get
            {
                return this.valorExtensoFaturaField;
            }
            set
            {
                this.valorExtensoFaturaField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.barueri.sp.gov.br/nfe")]
    public partial class ValoresServicoPrestado
    {
        
        private string quantidadeServicoField;
        
        private string valorUnitarioServicoField;
        
        private string valorServicosField;
        
        private string valorPisField;
        
        private string valorCofinsField;
        
        private string valorIrField;
        
        private string valorCsllField;
        
        private string valTotTributosField;
        
        private string valorIssField;
        
        private string valorNaoBaseCalculoField;
        
        private string aliquotaField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string QuantidadeServico
        {
            get
            {
                return this.quantidadeServicoField;
            }
            set
            {
                this.quantidadeServicoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string ValorUnitarioServico
        {
            get
            {
                return this.valorUnitarioServicoField;
            }
            set
            {
                this.valorUnitarioServicoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string ValorServicos
        {
            get
            {
                return this.valorServicosField;
            }
            set
            {
                this.valorServicosField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string ValorPis
        {
            get
            {
                return this.valorPisField;
            }
            set
            {
                this.valorPisField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string ValorCofins
        {
            get
            {
                return this.valorCofinsField;
            }
            set
            {
                this.valorCofinsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string ValorIr
        {
            get
            {
                return this.valorIrField;
            }
            set
            {
                this.valorIrField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string ValorCsll
        {
            get
            {
                return this.valorCsllField;
            }
            set
            {
                this.valorCsllField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string ValTotTributos
        {
            get
            {
                return this.valTotTributosField;
            }
            set
            {
                this.valTotTributosField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public string ValorIss
        {
            get
            {
                return this.valorIssField;
            }
            set
            {
                this.valorIssField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public string ValorNaoBaseCalculo
        {
            get
            {
                return this.valorNaoBaseCalculoField;
            }
            set
            {
                this.valorNaoBaseCalculoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public string Aliquota
        {
            get
            {
                return this.aliquotaField;
            }
            set
            {
                this.aliquotaField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.barueri.sp.gov.br/nfe")]
    public partial class ServicoPrestado
    {
        
        private ValoresServicoPrestado valoresServicoPrestadoField;
        
        private string issRetidoField;
        
        private string codigoServicoField;
        
        private string descricaoServicoField;
        
        private string discriminacaoField;
        
        private Fatura faturaField;
        
        private string observacaoLocalTributadoField;
        
        private string observacaoRegimeEspecialTributacaoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public ValoresServicoPrestado ValoresServicoPrestado
        {
            get
            {
                return this.valoresServicoPrestadoField;
            }
            set
            {
                this.valoresServicoPrestadoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string IssRetido
        {
            get
            {
                return this.issRetidoField;
            }
            set
            {
                this.issRetidoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string CodigoServico
        {
            get
            {
                return this.codigoServicoField;
            }
            set
            {
                this.codigoServicoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string DescricaoServico
        {
            get
            {
                return this.descricaoServicoField;
            }
            set
            {
                this.descricaoServicoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string Discriminacao
        {
            get
            {
                return this.discriminacaoField;
            }
            set
            {
                this.discriminacaoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public Fatura Fatura
        {
            get
            {
                return this.faturaField;
            }
            set
            {
                this.faturaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string ObservacaoLocalTributado
        {
            get
            {
                return this.observacaoLocalTributadoField;
            }
            set
            {
                this.observacaoLocalTributadoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string ObservacaoRegimeEspecialTributacao
        {
            get
            {
                return this.observacaoRegimeEspecialTributacaoField;
            }
            set
            {
                this.observacaoRegimeEspecialTributacaoField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.barueri.sp.gov.br/nfe")]
    public partial class InfDeclaracaoServicoPrestado
    {
        
        private Rps rpsField;
        
        private string competenciaField;
        
        private ServicoPrestado servicoPrestadoField;
        
        private Prestador prestadorField;
        
        private TomadorServico tomadorServicoField;
        
        private string regimeEspecialTributacaoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public Rps Rps
        {
            get
            {
                return this.rpsField;
            }
            set
            {
                this.rpsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Competencia
        {
            get
            {
                return this.competenciaField;
            }
            set
            {
                this.competenciaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public ServicoPrestado ServicoPrestado
        {
            get
            {
                return this.servicoPrestadoField;
            }
            set
            {
                this.servicoPrestadoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public Prestador Prestador
        {
            get
            {
                return this.prestadorField;
            }
            set
            {
                this.prestadorField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public TomadorServico TomadorServico
        {
            get
            {
                return this.tomadorServicoField;
            }
            set
            {
                this.tomadorServicoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string RegimeEspecialTributacao
        {
            get
            {
                return this.regimeEspecialTributacaoField;
            }
            set
            {
                this.regimeEspecialTributacaoField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.barueri.sp.gov.br/nfe")]
    public partial class Rps
    {
        
        private IdentificacaoRps identificacaoRpsField;
        
        private string dataEmissaoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public IdentificacaoRps IdentificacaoRps
        {
            get
            {
                return this.identificacaoRpsField;
            }
            set
            {
                this.identificacaoRpsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string DataEmissao
        {
            get
            {
                return this.dataEmissaoField;
            }
            set
            {
                this.dataEmissaoField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.barueri.sp.gov.br/nfe")]
    public partial class IdentificacaoRps
    {
        
        private string numeroField;
        
        private string serieField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Numero
        {
            get
            {
                return this.numeroField;
            }
            set
            {
                this.numeroField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Serie
        {
            get
            {
                return this.serieField;
            }
            set
            {
                this.serieField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.barueri.sp.gov.br/nfe")]
    public partial class TomadorServico
    {
        
        private IdentificacaoTomador identificacaoTomadorField;
        
        private string razaoSocialField;
        
        private Endereco enderecoField;
        
        private Contato contatoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public IdentificacaoTomador IdentificacaoTomador
        {
            get
            {
                return this.identificacaoTomadorField;
            }
            set
            {
                this.identificacaoTomadorField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string RazaoSocial
        {
            get
            {
                return this.razaoSocialField;
            }
            set
            {
                this.razaoSocialField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public Endereco Endereco
        {
            get
            {
                return this.enderecoField;
            }
            set
            {
                this.enderecoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public Contato Contato
        {
            get
            {
                return this.contatoField;
            }
            set
            {
                this.contatoField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.barueri.sp.gov.br/nfe")]
    public partial class IdentificacaoTomador
    {
        
        private CpfCnpj cpfCnpjField;
        
        private string inscricaoMunicipalField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public CpfCnpj CpfCnpj
        {
            get
            {
                return this.cpfCnpjField;
            }
            set
            {
                this.cpfCnpjField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string InscricaoMunicipal
        {
            get
            {
                return this.inscricaoMunicipalField;
            }
            set
            {
                this.inscricaoMunicipalField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.barueri.sp.gov.br/nfe")]
    public partial class Endereco
    {
        
        private string endereco1Field;
        
        private string numeroEnderecoField;
        
        private string complementoEnderecoField;
        
        private string bairroField;
        
        private string cidadeField;
        
        private string ufField;
        
        private string paisField;
        
        private string cepField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Endereco", Order=0)]
        public string Endereco1
        {
            get
            {
                return this.endereco1Field;
            }
            set
            {
                this.endereco1Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string NumeroEndereco
        {
            get
            {
                return this.numeroEnderecoField;
            }
            set
            {
                this.numeroEnderecoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string ComplementoEndereco
        {
            get
            {
                return this.complementoEnderecoField;
            }
            set
            {
                this.complementoEnderecoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string Bairro
        {
            get
            {
                return this.bairroField;
            }
            set
            {
                this.bairroField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string Cidade
        {
            get
            {
                return this.cidadeField;
            }
            set
            {
                this.cidadeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string Uf
        {
            get
            {
                return this.ufField;
            }
            set
            {
                this.ufField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string Pais
        {
            get
            {
                return this.paisField;
            }
            set
            {
                this.paisField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string Cep
        {
            get
            {
                return this.cepField;
            }
            set
            {
                this.cepField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.barueri.sp.gov.br/nfe")]
    public partial class Contato
    {
        
        private string telefoneField;
        
        private string emailField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Telefone
        {
            get
            {
                return this.telefoneField;
            }
            set
            {
                this.telefoneField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Email
        {
            get
            {
                return this.emailField;
            }
            set
            {
                this.emailField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.barueri.sp.gov.br/nfe")]
    public partial class DeclaracaoServicoPrestado
    {
        
        private InfDeclaracaoServicoPrestado infDeclaracaoServicoPrestadoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public InfDeclaracaoServicoPrestado InfDeclaracaoServicoPrestado
        {
            get
            {
                return this.infDeclaracaoServicoPrestadoField;
            }
            set
            {
                this.infDeclaracaoServicoPrestadoField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.barueri.sp.gov.br/nfe")]
    public partial class DadosInfNfeServPrestado
    {
        
        private int numeroNfeField;
        
        private string serieNfeField;
        
        private string descricaoNfeField;
        
        private string codigoVerificacaoField;
        
        private string dataEmissaoField;
        
        private string nfeSubstituidaField;
        
        private string dataEmissaoNfeSubstituidaField;
        
        private ValoresNFe valoresNfeField;
        
        private PrestadorServico prestadorServicoField;
        
        private DeclaracaoServicoPrestado declaracaoServicoPrestadoField;
        
        private DadosCartaCorrecaoNFe[] cartaCorrecaoField;
        
        private CancelamentoNFe cancelamentoNFeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int NumeroNfe
        {
            get
            {
                return this.numeroNfeField;
            }
            set
            {
                this.numeroNfeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string SerieNfe
        {
            get
            {
                return this.serieNfeField;
            }
            set
            {
                this.serieNfeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string DescricaoNfe
        {
            get
            {
                return this.descricaoNfeField;
            }
            set
            {
                this.descricaoNfeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string CodigoVerificacao
        {
            get
            {
                return this.codigoVerificacaoField;
            }
            set
            {
                this.codigoVerificacaoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string DataEmissao
        {
            get
            {
                return this.dataEmissaoField;
            }
            set
            {
                this.dataEmissaoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string NfeSubstituida
        {
            get
            {
                return this.nfeSubstituidaField;
            }
            set
            {
                this.nfeSubstituidaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string DataEmissaoNfeSubstituida
        {
            get
            {
                return this.dataEmissaoNfeSubstituidaField;
            }
            set
            {
                this.dataEmissaoNfeSubstituidaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public ValoresNFe ValoresNfe
        {
            get
            {
                return this.valoresNfeField;
            }
            set
            {
                this.valoresNfeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public PrestadorServico PrestadorServico
        {
            get
            {
                return this.prestadorServicoField;
            }
            set
            {
                this.prestadorServicoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public DeclaracaoServicoPrestado DeclaracaoServicoPrestado
        {
            get
            {
                return this.declaracaoServicoPrestadoField;
            }
            set
            {
                this.declaracaoServicoPrestadoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=10)]
        [System.Xml.Serialization.XmlArrayItemAttribute("InfCartaCorrecaoNfe", IsNullable=false)]
        public DadosCartaCorrecaoNFe[] CartaCorrecao
        {
            get
            {
                return this.cartaCorrecaoField;
            }
            set
            {
                this.cartaCorrecaoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=11)]
        public CancelamentoNFe CancelamentoNFe
        {
            get
            {
                return this.cancelamentoNFeField;
            }
            set
            {
                this.cancelamentoNFeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.barueri.sp.gov.br/nfe")]
    public partial class PrestadorServico
    {
        
        private IdentificacaoPrestador identificacaoPrestadorField;
        
        private string razaoSocialField;
        
        private string nomeFantasiaField;
        
        private Endereco enderecoField;
        
        private Contato contatoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public IdentificacaoPrestador IdentificacaoPrestador
        {
            get
            {
                return this.identificacaoPrestadorField;
            }
            set
            {
                this.identificacaoPrestadorField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string RazaoSocial
        {
            get
            {
                return this.razaoSocialField;
            }
            set
            {
                this.razaoSocialField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string NomeFantasia
        {
            get
            {
                return this.nomeFantasiaField;
            }
            set
            {
                this.nomeFantasiaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public Endereco Endereco
        {
            get
            {
                return this.enderecoField;
            }
            set
            {
                this.enderecoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public Contato Contato
        {
            get
            {
                return this.contatoField;
            }
            set
            {
                this.contatoField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.barueri.sp.gov.br/nfe")]
    public partial class InfNfeServPrestado
    {
        
        private DadosInfNfeServPrestado infNfeServPrestado1Field;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("InfNfeServPrestado", Order=0)]
        public DadosInfNfeServPrestado InfNfeServPrestado1
        {
            get
            {
                return this.infNfeServPrestado1Field;
            }
            set
            {
                this.infNfeServPrestado1Field = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.barueri.sp.gov.br/nfe")]
    public partial class NfeServPrestado
    {
        
        private InfNfeServPrestado nfeServPrestado1Field;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("NfeServPrestado", Order=0)]
        public InfNfeServPrestado NfeServPrestado1
        {
            get
            {
                return this.nfeServPrestado1Field;
            }
            set
            {
                this.nfeServPrestado1Field = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.barueri.sp.gov.br/nfe")]
    public partial class CompNfeServPrestado
    {
        
        private NfeServPrestado[] compNfeServPrestado1Field;
        
        private string paginaField;
        
        private string paginasField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("CompNfeServPrestado", Order=0)]
        public NfeServPrestado[] CompNfeServPrestado1
        {
            get
            {
                return this.compNfeServPrestado1Field;
            }
            set
            {
                this.compNfeServPrestado1Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Pagina
        {
            get
            {
                return this.paginaField;
            }
            set
            {
                this.paginaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string Paginas
        {
            get
            {
                return this.paginasField;
            }
            set
            {
                this.paginasField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.barueri.sp.gov.br/nfe")]
    public partial class ConsultarNfeServPrestadoResposta
    {
        
        private CompNfeServPrestado listaNfeServPrestadoField;
        
        private MensagemRetorno[] listaMensagemRetornoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public CompNfeServPrestado ListaNfeServPrestado
        {
            get
            {
                return this.listaNfeServPrestadoField;
            }
            set
            {
                this.listaNfeServPrestadoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ListaMensagemRetorno", Order=1)]
        public MensagemRetorno[] ListaMensagemRetorno
        {
            get
            {
                return this.listaMensagemRetornoField;
            }
            set
            {
                this.listaMensagemRetornoField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.barueri.sp.gov.br/nfe")]
    public partial class MensagemRetorno
    {
        
        private string codigoField;
        
        private string mensagemField;
        
        private string correcaoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Codigo
        {
            get
            {
                return this.codigoField;
            }
            set
            {
                this.codigoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Mensagem
        {
            get
            {
                return this.mensagemField;
            }
            set
            {
                this.mensagemField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string Correcao
        {
            get
            {
                return this.correcaoField;
            }
            set
            {
                this.correcaoField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.barueri.sp.gov.br/nfe")]
    public partial class ValoresDeclaracaoServico
    {
        
        private string valorServicosField;
        
        private string valorPisField;
        
        private string valorCofinsField;
        
        private string valorIrField;
        
        private string valorCsllField;
        
        private string valTotTributosField;
        
        private string valorIssField;
        
        private string aliquotaField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string ValorServicos
        {
            get
            {
                return this.valorServicosField;
            }
            set
            {
                this.valorServicosField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string ValorPis
        {
            get
            {
                return this.valorPisField;
            }
            set
            {
                this.valorPisField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string ValorCofins
        {
            get
            {
                return this.valorCofinsField;
            }
            set
            {
                this.valorCofinsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string ValorIr
        {
            get
            {
                return this.valorIrField;
            }
            set
            {
                this.valorIrField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string ValorCsll
        {
            get
            {
                return this.valorCsllField;
            }
            set
            {
                this.valorCsllField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string ValTotTributos
        {
            get
            {
                return this.valTotTributosField;
            }
            set
            {
                this.valTotTributosField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string ValorIss
        {
            get
            {
                return this.valorIssField;
            }
            set
            {
                this.valorIssField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string Aliquota
        {
            get
            {
                return this.aliquotaField;
            }
            set
            {
                this.aliquotaField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.barueri.sp.gov.br/nfe")]
    public partial class Servico
    {
        
        private ValoresDeclaracaoServico valoresField;
        
        private string issRetidoField;
        
        private string codigoServicoField;
        
        private string discriminacaoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public ValoresDeclaracaoServico Valores
        {
            get
            {
                return this.valoresField;
            }
            set
            {
                this.valoresField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string IssRetido
        {
            get
            {
                return this.issRetidoField;
            }
            set
            {
                this.issRetidoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string CodigoServico
        {
            get
            {
                return this.codigoServicoField;
            }
            set
            {
                this.codigoServicoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string Discriminacao
        {
            get
            {
                return this.discriminacaoField;
            }
            set
            {
                this.discriminacaoField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.barueri.sp.gov.br/nfe")]
    public partial class InfDeclaracaoPrestacaoServico
    {
        
        private Rps rpsField;
        
        private string competenciaField;
        
        private Servico servicoField;
        
        private IdentificacaoPrestador prestadorField;
        
        private TomadorServico tomadorServicoField;
        
        private string regimeEspecialTributacaoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public Rps Rps
        {
            get
            {
                return this.rpsField;
            }
            set
            {
                this.rpsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Competencia
        {
            get
            {
                return this.competenciaField;
            }
            set
            {
                this.competenciaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public Servico Servico
        {
            get
            {
                return this.servicoField;
            }
            set
            {
                this.servicoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public IdentificacaoPrestador Prestador
        {
            get
            {
                return this.prestadorField;
            }
            set
            {
                this.prestadorField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public TomadorServico TomadorServico
        {
            get
            {
                return this.tomadorServicoField;
            }
            set
            {
                this.tomadorServicoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string RegimeEspecialTributacao
        {
            get
            {
                return this.regimeEspecialTributacaoField;
            }
            set
            {
                this.regimeEspecialTributacaoField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.barueri.sp.gov.br/nfe")]
    public partial class DeclaracaoPrestacaoServico
    {
        
        private InfDeclaracaoPrestacaoServico infDeclaracaoPrestacaoServicoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public InfDeclaracaoPrestacaoServico InfDeclaracaoPrestacaoServico
        {
            get
            {
                return this.infDeclaracaoPrestacaoServicoField;
            }
            set
            {
                this.infDeclaracaoPrestacaoServicoField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    public interface wsGeraXmlSoapChannel : BarueriWebService.wsGeraXmlSoap, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    public partial class wsGeraXmlSoapClient : System.ServiceModel.ClientBase<BarueriWebService.wsGeraXmlSoap>, BarueriWebService.wsGeraXmlSoap
    {
        
        /// <summary>
        /// Implemente este método parcial para configurar o ponto de extremidade de serviço.
        /// </summary>
        /// <param name="serviceEndpoint">O ponto de extremidade a ser configurado</param>
        /// <param name="clientCredentials">As credenciais do cliente</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public wsGeraXmlSoapClient(EndpointConfiguration endpointConfiguration) : 
                base(wsGeraXmlSoapClient.GetBindingForEndpoint(endpointConfiguration), wsGeraXmlSoapClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public wsGeraXmlSoapClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(wsGeraXmlSoapClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public wsGeraXmlSoapClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(wsGeraXmlSoapClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public wsGeraXmlSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public BarueriWebService.ConsultarNfeResposta ConsultaNFeRecebidaPeriodo(int VersaoSchema, string MensagemXML)
        {
            return base.Channel.ConsultaNFeRecebidaPeriodo(VersaoSchema, MensagemXML);
        }
        
        public System.Threading.Tasks.Task<BarueriWebService.ConsultarNfeResposta> ConsultaNFeRecebidaPeriodoAsync(int VersaoSchema, string MensagemXML)
        {
            return base.Channel.ConsultaNFeRecebidaPeriodoAsync(VersaoSchema, MensagemXML);
        }
        
        public BarueriWebService.ConsultarNfeResposta ConsultaNFeRecebidaCompetencia(int VersaoSchema, string MensagemXML)
        {
            return base.Channel.ConsultaNFeRecebidaCompetencia(VersaoSchema, MensagemXML);
        }
        
        public System.Threading.Tasks.Task<BarueriWebService.ConsultarNfeResposta> ConsultaNFeRecebidaCompetenciaAsync(int VersaoSchema, string MensagemXML)
        {
            return base.Channel.ConsultaNFeRecebidaCompetenciaAsync(VersaoSchema, MensagemXML);
        }
        
        public BarueriWebService.ConsultarNfeResposta ConsultaNFeRecebidaNumero(int VersaoSchema, string MensagemXML)
        {
            return base.Channel.ConsultaNFeRecebidaNumero(VersaoSchema, MensagemXML);
        }
        
        public System.Threading.Tasks.Task<BarueriWebService.ConsultarNfeResposta> ConsultaNFeRecebidaNumeroAsync(int VersaoSchema, string MensagemXML)
        {
            return base.Channel.ConsultaNFeRecebidaNumeroAsync(VersaoSchema, MensagemXML);
        }
        
        public BarueriWebService.ConsultarNfeServPrestadoResposta ConsultaNFeAutencididade(string CodigoAutenticidade, string CPFCNPJTomador)
        {
            return base.Channel.ConsultaNFeAutencididade(CodigoAutenticidade, CPFCNPJTomador);
        }
        
        public System.Threading.Tasks.Task<BarueriWebService.ConsultarNfeServPrestadoResposta> ConsultaNFeAutencididadeAsync(string CodigoAutenticidade, string CPFCNPJTomador)
        {
            return base.Channel.ConsultaNFeAutencididadeAsync(CodigoAutenticidade, CPFCNPJTomador);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.wsGeraXmlSoap))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                result.Security.Mode = System.ServiceModel.BasicHttpSecurityMode.Transport;
                return result;
            }
            if ((endpointConfiguration == EndpointConfiguration.wsGeraXmlSoap12))
            {
                System.ServiceModel.Channels.CustomBinding result = new System.ServiceModel.Channels.CustomBinding();
                System.ServiceModel.Channels.TextMessageEncodingBindingElement textBindingElement = new System.ServiceModel.Channels.TextMessageEncodingBindingElement();
                textBindingElement.MessageVersion = System.ServiceModel.Channels.MessageVersion.CreateVersion(System.ServiceModel.EnvelopeVersion.Soap12, System.ServiceModel.Channels.AddressingVersion.None);
                result.Elements.Add(textBindingElement);
                System.ServiceModel.Channels.HttpsTransportBindingElement httpsBindingElement = new System.ServiceModel.Channels.HttpsTransportBindingElement();
                httpsBindingElement.AllowCookies = true;
                httpsBindingElement.MaxBufferSize = int.MaxValue;
                httpsBindingElement.MaxReceivedMessageSize = int.MaxValue;
                httpsBindingElement.RequireClientCertificate = true;
                result.Elements.Add(httpsBindingElement);
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Não foi possível encontrar o ponto de extremidade com o nome \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.wsGeraXmlSoap))
            {
                return new System.ServiceModel.EndpointAddress("https://servicos.barueri.sp.gov.br/nfewsxml/wsgeraxml.asmx");
            }
            if ((endpointConfiguration == EndpointConfiguration.wsGeraXmlSoap12))
            {
                return new System.ServiceModel.EndpointAddress("https://servicos.barueri.sp.gov.br/nfewsxml/wsgeraxml.asmx");
            }
            throw new System.InvalidOperationException(string.Format("Não foi possível encontrar o ponto de extremidade com o nome \'{0}\'.", endpointConfiguration));
        }
        
        public enum EndpointConfiguration
        {
            
            wsGeraXmlSoap,
            
            wsGeraXmlSoap12,
        }
    }
}
