//------------------------------------------------------------------------------
// <auto-generated>
//     Esse código foi gerado por uma ferramenta.
//
//     As alterações no arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UberlandiaWebService
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://udigital.uberlandia.mg.gov.br/WsNFe2/LoteRps.jws", ConfigurationName="UberlandiaWebService.LoteRps")]
    public interface LoteRps
    {
        
        // CODEGEN: Gerando contrato de mensagem porque o namespace do wrapper (http://proces.wsnfe2.dsfnet.com.br) da mensagem consultarSequencialRpsRequest não corresponde ao valor padrão (http://udigital.uberlandia.mg.gov.br/WsNFe2/LoteRps.jws)
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        UberlandiaWebService.consultarSequencialRpsResponse consultarSequencialRps(UberlandiaWebService.consultarSequencialRpsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<UberlandiaWebService.consultarSequencialRpsResponse> consultarSequencialRpsAsync(UberlandiaWebService.consultarSequencialRpsRequest request);
        
        // CODEGEN: Gerando contrato de mensagem porque o namespace do wrapper (http://proces.wsnfe2.dsfnet.com.br) da mensagem enviarSincronoRequest não corresponde ao valor padrão (http://udigital.uberlandia.mg.gov.br/WsNFe2/LoteRps.jws)
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        UberlandiaWebService.enviarSincronoResponse enviarSincrono(UberlandiaWebService.enviarSincronoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<UberlandiaWebService.enviarSincronoResponse> enviarSincronoAsync(UberlandiaWebService.enviarSincronoRequest request);
        
        // CODEGEN: Gerando contrato de mensagem porque o namespace do wrapper (http://proces.wsnfe2.dsfnet.com.br) da mensagem enviarRequest não corresponde ao valor padrão (http://udigital.uberlandia.mg.gov.br/WsNFe2/LoteRps.jws)
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        UberlandiaWebService.enviarResponse enviar(UberlandiaWebService.enviarRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<UberlandiaWebService.enviarResponse> enviarAsync(UberlandiaWebService.enviarRequest request);
        
        // CODEGEN: Gerando contrato de mensagem porque o namespace do wrapper (http://proces.wsnfe2.dsfnet.com.br) da mensagem testeEnviarRequest não corresponde ao valor padrão (http://udigital.uberlandia.mg.gov.br/WsNFe2/LoteRps.jws)
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        UberlandiaWebService.testeEnviarResponse testeEnviar(UberlandiaWebService.testeEnviarRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<UberlandiaWebService.testeEnviarResponse> testeEnviarAsync(UberlandiaWebService.testeEnviarRequest request);
        
        // CODEGEN: Gerando contrato de mensagem porque o namespace do wrapper (http://proces.wsnfe2.dsfnet.com.br) da mensagem consultarLoteRequest não corresponde ao valor padrão (http://udigital.uberlandia.mg.gov.br/WsNFe2/LoteRps.jws)
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        UberlandiaWebService.consultarLoteResponse consultarLote(UberlandiaWebService.consultarLoteRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<UberlandiaWebService.consultarLoteResponse> consultarLoteAsync(UberlandiaWebService.consultarLoteRequest request);
        
        // CODEGEN: Gerando contrato de mensagem porque o namespace do wrapper (http://proces.wsnfe2.dsfnet.com.br) da mensagem consultarAliquotaSimplesNacionalRequest não corresponde ao valor padrão (http://udigital.uberlandia.mg.gov.br/WsNFe2/LoteRps.jws)
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        UberlandiaWebService.consultarAliquotaSimplesNacionalResponse consultarAliquotaSimplesNacional(UberlandiaWebService.consultarAliquotaSimplesNacionalRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<UberlandiaWebService.consultarAliquotaSimplesNacionalResponse> consultarAliquotaSimplesNacionalAsync(UberlandiaWebService.consultarAliquotaSimplesNacionalRequest request);
        
        // CODEGEN: Gerando contrato de mensagem porque o namespace do wrapper (http://proces.wsnfe2.dsfnet.com.br) da mensagem consultarNotaTomadaRequest não corresponde ao valor padrão (http://udigital.uberlandia.mg.gov.br/WsNFe2/LoteRps.jws)
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        UberlandiaWebService.consultarNotaTomadaResponse consultarNotaTomada(UberlandiaWebService.consultarNotaTomadaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<UberlandiaWebService.consultarNotaTomadaResponse> consultarNotaTomadaAsync(UberlandiaWebService.consultarNotaTomadaRequest request);
        
        // CODEGEN: Gerando contrato de mensagem porque o namespace do wrapper (http://proces.wsnfe2.dsfnet.com.br) da mensagem consultarNotaRequest não corresponde ao valor padrão (http://udigital.uberlandia.mg.gov.br/WsNFe2/LoteRps.jws)
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        UberlandiaWebService.consultarNotaResponse consultarNota(UberlandiaWebService.consultarNotaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<UberlandiaWebService.consultarNotaResponse> consultarNotaAsync(UberlandiaWebService.consultarNotaRequest request);
        
        // CODEGEN: Gerando contrato de mensagem porque o namespace do wrapper (http://proces.wsnfe2.dsfnet.com.br) da mensagem cancelarRequest não corresponde ao valor padrão (http://udigital.uberlandia.mg.gov.br/WsNFe2/LoteRps.jws)
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        UberlandiaWebService.cancelarResponse cancelar(UberlandiaWebService.cancelarRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<UberlandiaWebService.cancelarResponse> cancelarAsync(UberlandiaWebService.cancelarRequest request);
        
        // CODEGEN: Gerando contrato de mensagem porque o namespace do wrapper (http://proces.wsnfe2.dsfnet.com.br) da mensagem consultarNFSeRpsRequest não corresponde ao valor padrão (http://udigital.uberlandia.mg.gov.br/WsNFe2/LoteRps.jws)
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        UberlandiaWebService.consultarNFSeRpsResponse consultarNFSeRps(UberlandiaWebService.consultarNFSeRpsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<UberlandiaWebService.consultarNFSeRpsResponse> consultarNFSeRpsAsync(UberlandiaWebService.consultarNFSeRpsRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="consultarSequencialRps", WrapperNamespace="http://proces.wsnfe2.dsfnet.com.br", IsWrapped=true)]
    public partial class consultarSequencialRpsRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string mensagemXml;
        
        public consultarSequencialRpsRequest()
        {
        }
        
        public consultarSequencialRpsRequest(string mensagemXml)
        {
            this.mensagemXml = mensagemXml;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="consultarSequencialRpsResponse", WrapperNamespace="http://udigital.uberlandia.mg.gov.br/WsNFe2/LoteRps.jws", IsWrapped=true)]
    public partial class consultarSequencialRpsResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string consultarSequencialRpsReturn;
        
        public consultarSequencialRpsResponse()
        {
        }
        
        public consultarSequencialRpsResponse(string consultarSequencialRpsReturn)
        {
            this.consultarSequencialRpsReturn = consultarSequencialRpsReturn;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="enviarSincrono", WrapperNamespace="http://proces.wsnfe2.dsfnet.com.br", IsWrapped=true)]
    public partial class enviarSincronoRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string mensagemXml;
        
        public enviarSincronoRequest()
        {
        }
        
        public enviarSincronoRequest(string mensagemXml)
        {
            this.mensagemXml = mensagemXml;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="enviarSincronoResponse", WrapperNamespace="http://udigital.uberlandia.mg.gov.br/WsNFe2/LoteRps.jws", IsWrapped=true)]
    public partial class enviarSincronoResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string enviarSincronoReturn;
        
        public enviarSincronoResponse()
        {
        }
        
        public enviarSincronoResponse(string enviarSincronoReturn)
        {
            this.enviarSincronoReturn = enviarSincronoReturn;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="enviar", WrapperNamespace="http://proces.wsnfe2.dsfnet.com.br", IsWrapped=true)]
    public partial class enviarRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string mensagemXml;
        
        public enviarRequest()
        {
        }
        
        public enviarRequest(string mensagemXml)
        {
            this.mensagemXml = mensagemXml;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="enviarResponse", WrapperNamespace="http://udigital.uberlandia.mg.gov.br/WsNFe2/LoteRps.jws", IsWrapped=true)]
    public partial class enviarResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string enviarReturn;
        
        public enviarResponse()
        {
        }
        
        public enviarResponse(string enviarReturn)
        {
            this.enviarReturn = enviarReturn;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="testeEnviar", WrapperNamespace="http://proces.wsnfe2.dsfnet.com.br", IsWrapped=true)]
    public partial class testeEnviarRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string mensagemXml;
        
        public testeEnviarRequest()
        {
        }
        
        public testeEnviarRequest(string mensagemXml)
        {
            this.mensagemXml = mensagemXml;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="testeEnviarResponse", WrapperNamespace="http://udigital.uberlandia.mg.gov.br/WsNFe2/LoteRps.jws", IsWrapped=true)]
    public partial class testeEnviarResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string testeEnviarReturn;
        
        public testeEnviarResponse()
        {
        }
        
        public testeEnviarResponse(string testeEnviarReturn)
        {
            this.testeEnviarReturn = testeEnviarReturn;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="consultarLote", WrapperNamespace="http://proces.wsnfe2.dsfnet.com.br", IsWrapped=true)]
    public partial class consultarLoteRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string mensagemXml;
        
        public consultarLoteRequest()
        {
        }
        
        public consultarLoteRequest(string mensagemXml)
        {
            this.mensagemXml = mensagemXml;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="consultarLoteResponse", WrapperNamespace="http://udigital.uberlandia.mg.gov.br/WsNFe2/LoteRps.jws", IsWrapped=true)]
    public partial class consultarLoteResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string consultarLoteReturn;
        
        public consultarLoteResponse()
        {
        }
        
        public consultarLoteResponse(string consultarLoteReturn)
        {
            this.consultarLoteReturn = consultarLoteReturn;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="consultarAliquotaSimplesNacional", WrapperNamespace="http://proces.wsnfe2.dsfnet.com.br", IsWrapped=true)]
    public partial class consultarAliquotaSimplesNacionalRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string cpfResponsavel;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public string ultimaAtualizacao;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=2)]
        public string codCid;
        
        public consultarAliquotaSimplesNacionalRequest()
        {
        }
        
        public consultarAliquotaSimplesNacionalRequest(string cpfResponsavel, string ultimaAtualizacao, string codCid)
        {
            this.cpfResponsavel = cpfResponsavel;
            this.ultimaAtualizacao = ultimaAtualizacao;
            this.codCid = codCid;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="consultarAliquotaSimplesNacionalResponse", WrapperNamespace="http://udigital.uberlandia.mg.gov.br/WsNFe2/LoteRps.jws", IsWrapped=true)]
    public partial class consultarAliquotaSimplesNacionalResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string consultarAliquotaSimplesNacionalReturn;
        
        public consultarAliquotaSimplesNacionalResponse()
        {
        }
        
        public consultarAliquotaSimplesNacionalResponse(string consultarAliquotaSimplesNacionalReturn)
        {
            this.consultarAliquotaSimplesNacionalReturn = consultarAliquotaSimplesNacionalReturn;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="consultarNotaTomada", WrapperNamespace="http://proces.wsnfe2.dsfnet.com.br", IsWrapped=true)]
    public partial class consultarNotaTomadaRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string mensagemXml;
        
        public consultarNotaTomadaRequest()
        {
        }
        
        public consultarNotaTomadaRequest(string mensagemXml)
        {
            this.mensagemXml = mensagemXml;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="consultarNotaTomadaResponse", WrapperNamespace="http://udigital.uberlandia.mg.gov.br/WsNFe2/LoteRps.jws", IsWrapped=true)]
    public partial class consultarNotaTomadaResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string consultarNotaTomadaReturn;
        
        public consultarNotaTomadaResponse()
        {
        }
        
        public consultarNotaTomadaResponse(string consultarNotaTomadaReturn)
        {
            this.consultarNotaTomadaReturn = consultarNotaTomadaReturn;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="consultarNota", WrapperNamespace="http://proces.wsnfe2.dsfnet.com.br", IsWrapped=true)]
    public partial class consultarNotaRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string mensagemXml;
        
        public consultarNotaRequest()
        {
        }
        
        public consultarNotaRequest(string mensagemXml)
        {
            this.mensagemXml = mensagemXml;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="consultarNotaResponse", WrapperNamespace="http://udigital.uberlandia.mg.gov.br/WsNFe2/LoteRps.jws", IsWrapped=true)]
    public partial class consultarNotaResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string consultarNotaReturn;
        
        public consultarNotaResponse()
        {
        }
        
        public consultarNotaResponse(string consultarNotaReturn)
        {
            this.consultarNotaReturn = consultarNotaReturn;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="cancelar", WrapperNamespace="http://proces.wsnfe2.dsfnet.com.br", IsWrapped=true)]
    public partial class cancelarRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string mensagemXml;
        
        public cancelarRequest()
        {
        }
        
        public cancelarRequest(string mensagemXml)
        {
            this.mensagemXml = mensagemXml;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="cancelarResponse", WrapperNamespace="http://udigital.uberlandia.mg.gov.br/WsNFe2/LoteRps.jws", IsWrapped=true)]
    public partial class cancelarResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string cancelarReturn;
        
        public cancelarResponse()
        {
        }
        
        public cancelarResponse(string cancelarReturn)
        {
            this.cancelarReturn = cancelarReturn;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="consultarNFSeRps", WrapperNamespace="http://proces.wsnfe2.dsfnet.com.br", IsWrapped=true)]
    public partial class consultarNFSeRpsRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string mensagemXml;
        
        public consultarNFSeRpsRequest()
        {
        }
        
        public consultarNFSeRpsRequest(string mensagemXml)
        {
            this.mensagemXml = mensagemXml;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="consultarNFSeRpsResponse", WrapperNamespace="http://udigital.uberlandia.mg.gov.br/WsNFe2/LoteRps.jws", IsWrapped=true)]
    public partial class consultarNFSeRpsResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string consultarNFSeRpsReturn;
        
        public consultarNFSeRpsResponse()
        {
        }
        
        public consultarNFSeRpsResponse(string consultarNFSeRpsReturn)
        {
            this.consultarNFSeRpsReturn = consultarNFSeRpsReturn;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    public interface LoteRpsChannel : UberlandiaWebService.LoteRps, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    public partial class LoteRpsClient : System.ServiceModel.ClientBase<UberlandiaWebService.LoteRps>, UberlandiaWebService.LoteRps
    {
        
        /// <summary>
        /// Implemente este método parcial para configurar o ponto de extremidade de serviço.
        /// </summary>
        /// <param name="serviceEndpoint">O ponto de extremidade a ser configurado</param>
        /// <param name="clientCredentials">As credenciais do cliente</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public LoteRpsClient() : 
                base(LoteRpsClient.GetDefaultBinding(), LoteRpsClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.LoteRps.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public LoteRpsClient(EndpointConfiguration endpointConfiguration) : 
                base(LoteRpsClient.GetBindingForEndpoint(endpointConfiguration), LoteRpsClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public LoteRpsClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(LoteRpsClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public LoteRpsClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(LoteRpsClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public LoteRpsClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        UberlandiaWebService.consultarSequencialRpsResponse UberlandiaWebService.LoteRps.consultarSequencialRps(UberlandiaWebService.consultarSequencialRpsRequest request)
        {
            return base.Channel.consultarSequencialRps(request);
        }
        
        public string consultarSequencialRps(string mensagemXml)
        {
            UberlandiaWebService.consultarSequencialRpsRequest inValue = new UberlandiaWebService.consultarSequencialRpsRequest();
            inValue.mensagemXml = mensagemXml;
            UberlandiaWebService.consultarSequencialRpsResponse retVal = ((UberlandiaWebService.LoteRps)(this)).consultarSequencialRps(inValue);
            return retVal.consultarSequencialRpsReturn;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<UberlandiaWebService.consultarSequencialRpsResponse> UberlandiaWebService.LoteRps.consultarSequencialRpsAsync(UberlandiaWebService.consultarSequencialRpsRequest request)
        {
            return base.Channel.consultarSequencialRpsAsync(request);
        }
        
        public System.Threading.Tasks.Task<UberlandiaWebService.consultarSequencialRpsResponse> consultarSequencialRpsAsync(string mensagemXml)
        {
            UberlandiaWebService.consultarSequencialRpsRequest inValue = new UberlandiaWebService.consultarSequencialRpsRequest();
            inValue.mensagemXml = mensagemXml;
            return ((UberlandiaWebService.LoteRps)(this)).consultarSequencialRpsAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        UberlandiaWebService.enviarSincronoResponse UberlandiaWebService.LoteRps.enviarSincrono(UberlandiaWebService.enviarSincronoRequest request)
        {
            return base.Channel.enviarSincrono(request);
        }
        
        public string enviarSincrono(string mensagemXml)
        {
            UberlandiaWebService.enviarSincronoRequest inValue = new UberlandiaWebService.enviarSincronoRequest();
            inValue.mensagemXml = mensagemXml;
            UberlandiaWebService.enviarSincronoResponse retVal = ((UberlandiaWebService.LoteRps)(this)).enviarSincrono(inValue);
            return retVal.enviarSincronoReturn;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<UberlandiaWebService.enviarSincronoResponse> UberlandiaWebService.LoteRps.enviarSincronoAsync(UberlandiaWebService.enviarSincronoRequest request)
        {
            return base.Channel.enviarSincronoAsync(request);
        }
        
        public System.Threading.Tasks.Task<UberlandiaWebService.enviarSincronoResponse> enviarSincronoAsync(string mensagemXml)
        {
            UberlandiaWebService.enviarSincronoRequest inValue = new UberlandiaWebService.enviarSincronoRequest();
            inValue.mensagemXml = mensagemXml;
            return ((UberlandiaWebService.LoteRps)(this)).enviarSincronoAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        UberlandiaWebService.enviarResponse UberlandiaWebService.LoteRps.enviar(UberlandiaWebService.enviarRequest request)
        {
            return base.Channel.enviar(request);
        }
        
        public string enviar(string mensagemXml)
        {
            UberlandiaWebService.enviarRequest inValue = new UberlandiaWebService.enviarRequest();
            inValue.mensagemXml = mensagemXml;
            UberlandiaWebService.enviarResponse retVal = ((UberlandiaWebService.LoteRps)(this)).enviar(inValue);
            return retVal.enviarReturn;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<UberlandiaWebService.enviarResponse> UberlandiaWebService.LoteRps.enviarAsync(UberlandiaWebService.enviarRequest request)
        {
            return base.Channel.enviarAsync(request);
        }
        
        public System.Threading.Tasks.Task<UberlandiaWebService.enviarResponse> enviarAsync(string mensagemXml)
        {
            UberlandiaWebService.enviarRequest inValue = new UberlandiaWebService.enviarRequest();
            inValue.mensagemXml = mensagemXml;
            return ((UberlandiaWebService.LoteRps)(this)).enviarAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        UberlandiaWebService.testeEnviarResponse UberlandiaWebService.LoteRps.testeEnviar(UberlandiaWebService.testeEnviarRequest request)
        {
            return base.Channel.testeEnviar(request);
        }
        
        public string testeEnviar(string mensagemXml)
        {
            UberlandiaWebService.testeEnviarRequest inValue = new UberlandiaWebService.testeEnviarRequest();
            inValue.mensagemXml = mensagemXml;
            UberlandiaWebService.testeEnviarResponse retVal = ((UberlandiaWebService.LoteRps)(this)).testeEnviar(inValue);
            return retVal.testeEnviarReturn;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<UberlandiaWebService.testeEnviarResponse> UberlandiaWebService.LoteRps.testeEnviarAsync(UberlandiaWebService.testeEnviarRequest request)
        {
            return base.Channel.testeEnviarAsync(request);
        }
        
        public System.Threading.Tasks.Task<UberlandiaWebService.testeEnviarResponse> testeEnviarAsync(string mensagemXml)
        {
            UberlandiaWebService.testeEnviarRequest inValue = new UberlandiaWebService.testeEnviarRequest();
            inValue.mensagemXml = mensagemXml;
            return ((UberlandiaWebService.LoteRps)(this)).testeEnviarAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        UberlandiaWebService.consultarLoteResponse UberlandiaWebService.LoteRps.consultarLote(UberlandiaWebService.consultarLoteRequest request)
        {
            return base.Channel.consultarLote(request);
        }
        
        public string consultarLote(string mensagemXml)
        {
            UberlandiaWebService.consultarLoteRequest inValue = new UberlandiaWebService.consultarLoteRequest();
            inValue.mensagemXml = mensagemXml;
            UberlandiaWebService.consultarLoteResponse retVal = ((UberlandiaWebService.LoteRps)(this)).consultarLote(inValue);
            return retVal.consultarLoteReturn;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<UberlandiaWebService.consultarLoteResponse> UberlandiaWebService.LoteRps.consultarLoteAsync(UberlandiaWebService.consultarLoteRequest request)
        {
            return base.Channel.consultarLoteAsync(request);
        }
        
        public System.Threading.Tasks.Task<UberlandiaWebService.consultarLoteResponse> consultarLoteAsync(string mensagemXml)
        {
            UberlandiaWebService.consultarLoteRequest inValue = new UberlandiaWebService.consultarLoteRequest();
            inValue.mensagemXml = mensagemXml;
            return ((UberlandiaWebService.LoteRps)(this)).consultarLoteAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        UberlandiaWebService.consultarAliquotaSimplesNacionalResponse UberlandiaWebService.LoteRps.consultarAliquotaSimplesNacional(UberlandiaWebService.consultarAliquotaSimplesNacionalRequest request)
        {
            return base.Channel.consultarAliquotaSimplesNacional(request);
        }
        
        public string consultarAliquotaSimplesNacional(string cpfResponsavel, string ultimaAtualizacao, string codCid)
        {
            UberlandiaWebService.consultarAliquotaSimplesNacionalRequest inValue = new UberlandiaWebService.consultarAliquotaSimplesNacionalRequest();
            inValue.cpfResponsavel = cpfResponsavel;
            inValue.ultimaAtualizacao = ultimaAtualizacao;
            inValue.codCid = codCid;
            UberlandiaWebService.consultarAliquotaSimplesNacionalResponse retVal = ((UberlandiaWebService.LoteRps)(this)).consultarAliquotaSimplesNacional(inValue);
            return retVal.consultarAliquotaSimplesNacionalReturn;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<UberlandiaWebService.consultarAliquotaSimplesNacionalResponse> UberlandiaWebService.LoteRps.consultarAliquotaSimplesNacionalAsync(UberlandiaWebService.consultarAliquotaSimplesNacionalRequest request)
        {
            return base.Channel.consultarAliquotaSimplesNacionalAsync(request);
        }
        
        public System.Threading.Tasks.Task<UberlandiaWebService.consultarAliquotaSimplesNacionalResponse> consultarAliquotaSimplesNacionalAsync(string cpfResponsavel, string ultimaAtualizacao, string codCid)
        {
            UberlandiaWebService.consultarAliquotaSimplesNacionalRequest inValue = new UberlandiaWebService.consultarAliquotaSimplesNacionalRequest();
            inValue.cpfResponsavel = cpfResponsavel;
            inValue.ultimaAtualizacao = ultimaAtualizacao;
            inValue.codCid = codCid;
            return ((UberlandiaWebService.LoteRps)(this)).consultarAliquotaSimplesNacionalAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        UberlandiaWebService.consultarNotaTomadaResponse UberlandiaWebService.LoteRps.consultarNotaTomada(UberlandiaWebService.consultarNotaTomadaRequest request)
        {
            return base.Channel.consultarNotaTomada(request);
        }
        
        public string consultarNotaTomada(string mensagemXml)
        {
            UberlandiaWebService.consultarNotaTomadaRequest inValue = new UberlandiaWebService.consultarNotaTomadaRequest();
            inValue.mensagemXml = mensagemXml;
            UberlandiaWebService.consultarNotaTomadaResponse retVal = ((UberlandiaWebService.LoteRps)(this)).consultarNotaTomada(inValue);
            return retVal.consultarNotaTomadaReturn;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<UberlandiaWebService.consultarNotaTomadaResponse> UberlandiaWebService.LoteRps.consultarNotaTomadaAsync(UberlandiaWebService.consultarNotaTomadaRequest request)
        {
            return base.Channel.consultarNotaTomadaAsync(request);
        }
        
        public System.Threading.Tasks.Task<UberlandiaWebService.consultarNotaTomadaResponse> consultarNotaTomadaAsync(string mensagemXml)
        {
            UberlandiaWebService.consultarNotaTomadaRequest inValue = new UberlandiaWebService.consultarNotaTomadaRequest();
            inValue.mensagemXml = mensagemXml;
            return ((UberlandiaWebService.LoteRps)(this)).consultarNotaTomadaAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        UberlandiaWebService.consultarNotaResponse UberlandiaWebService.LoteRps.consultarNota(UberlandiaWebService.consultarNotaRequest request)
        {
            return base.Channel.consultarNota(request);
        }
        
        public string consultarNota(string mensagemXml)
        {
            UberlandiaWebService.consultarNotaRequest inValue = new UberlandiaWebService.consultarNotaRequest();
            inValue.mensagemXml = mensagemXml;
            UberlandiaWebService.consultarNotaResponse retVal = ((UberlandiaWebService.LoteRps)(this)).consultarNota(inValue);
            return retVal.consultarNotaReturn;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<UberlandiaWebService.consultarNotaResponse> UberlandiaWebService.LoteRps.consultarNotaAsync(UberlandiaWebService.consultarNotaRequest request)
        {
            return base.Channel.consultarNotaAsync(request);
        }
        
        public System.Threading.Tasks.Task<UberlandiaWebService.consultarNotaResponse> consultarNotaAsync(string mensagemXml)
        {
            UberlandiaWebService.consultarNotaRequest inValue = new UberlandiaWebService.consultarNotaRequest();
            inValue.mensagemXml = mensagemXml;
            return ((UberlandiaWebService.LoteRps)(this)).consultarNotaAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        UberlandiaWebService.cancelarResponse UberlandiaWebService.LoteRps.cancelar(UberlandiaWebService.cancelarRequest request)
        {
            return base.Channel.cancelar(request);
        }
        
        public string cancelar(string mensagemXml)
        {
            UberlandiaWebService.cancelarRequest inValue = new UberlandiaWebService.cancelarRequest();
            inValue.mensagemXml = mensagemXml;
            UberlandiaWebService.cancelarResponse retVal = ((UberlandiaWebService.LoteRps)(this)).cancelar(inValue);
            return retVal.cancelarReturn;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<UberlandiaWebService.cancelarResponse> UberlandiaWebService.LoteRps.cancelarAsync(UberlandiaWebService.cancelarRequest request)
        {
            return base.Channel.cancelarAsync(request);
        }
        
        public System.Threading.Tasks.Task<UberlandiaWebService.cancelarResponse> cancelarAsync(string mensagemXml)
        {
            UberlandiaWebService.cancelarRequest inValue = new UberlandiaWebService.cancelarRequest();
            inValue.mensagemXml = mensagemXml;
            return ((UberlandiaWebService.LoteRps)(this)).cancelarAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        UberlandiaWebService.consultarNFSeRpsResponse UberlandiaWebService.LoteRps.consultarNFSeRps(UberlandiaWebService.consultarNFSeRpsRequest request)
        {
            return base.Channel.consultarNFSeRps(request);
        }
        
        public string consultarNFSeRps(string mensagemXml)
        {
            UberlandiaWebService.consultarNFSeRpsRequest inValue = new UberlandiaWebService.consultarNFSeRpsRequest();
            inValue.mensagemXml = mensagemXml;
            UberlandiaWebService.consultarNFSeRpsResponse retVal = ((UberlandiaWebService.LoteRps)(this)).consultarNFSeRps(inValue);
            return retVal.consultarNFSeRpsReturn;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<UberlandiaWebService.consultarNFSeRpsResponse> UberlandiaWebService.LoteRps.consultarNFSeRpsAsync(UberlandiaWebService.consultarNFSeRpsRequest request)
        {
            return base.Channel.consultarNFSeRpsAsync(request);
        }
        
        public System.Threading.Tasks.Task<UberlandiaWebService.consultarNFSeRpsResponse> consultarNFSeRpsAsync(string mensagemXml)
        {
            UberlandiaWebService.consultarNFSeRpsRequest inValue = new UberlandiaWebService.consultarNFSeRpsRequest();
            inValue.mensagemXml = mensagemXml;
            return ((UberlandiaWebService.LoteRps)(this)).consultarNFSeRpsAsync(inValue);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.LoteRps))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Não foi possível encontrar o ponto de extremidade com o nome \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.LoteRps))
            {
                return new System.ServiceModel.EndpointAddress("http://udigital.uberlandia.mg.gov.br/WsNFe2/LoteRps.jws");
            }
            throw new System.InvalidOperationException(string.Format("Não foi possível encontrar o ponto de extremidade com o nome \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return LoteRpsClient.GetBindingForEndpoint(EndpointConfiguration.LoteRps);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return LoteRpsClient.GetEndpointAddress(EndpointConfiguration.LoteRps);
        }
        
        public enum EndpointConfiguration
        {
            
            LoteRps,
        }
    }
}
