//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AmericanaWebService
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.nfe.com.br/", ConfigurationName="AmericanaWebService.NFSESoap")]
    public interface NFSESoap
    {
        
        // CODEGEN: Generating message contract since the wrapper name (ConsultarNfseRequest) of message ConsultarNfseRequest does not match the default value (ConsultarNfse)
        [System.ServiceModel.OperationContractAttribute(Action="http://www.nfe.com.br/ConsultarNfse", ReplyAction="*")]
        AmericanaWebService.ConsultarNfseResponse ConsultarNfse(AmericanaWebService.ConsultarNfseRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.nfe.com.br/ConsultarNfse", ReplyAction="*")]
        System.Threading.Tasks.Task<AmericanaWebService.ConsultarNfseResponse> ConsultarNfseAsync(AmericanaWebService.ConsultarNfseRequest request);
        
        // CODEGEN: Generating message contract since the wrapper name (ConsultarNfsePorRpsRequest) of message ConsultarNfsePorRpsRequest does not match the default value (ConsultarNfsePorRps)
        [System.ServiceModel.OperationContractAttribute(Action="http://www.nfe.com.br/ConsultarNfsePorRps", ReplyAction="*")]
        AmericanaWebService.ConsultarNfsePorRpsResponse ConsultarNfsePorRps(AmericanaWebService.ConsultarNfsePorRpsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.nfe.com.br/ConsultarNfsePorRps", ReplyAction="*")]
        System.Threading.Tasks.Task<AmericanaWebService.ConsultarNfsePorRpsResponse> ConsultarNfsePorRpsAsync(AmericanaWebService.ConsultarNfsePorRpsRequest request);
        
        // CODEGEN: Generating message contract since the wrapper name (ConsultarLoteRpsRequest) of message ConsultarLoteRpsRequest does not match the default value (ConsultarLoteRps)
        [System.ServiceModel.OperationContractAttribute(Action="http://www.nfe.com.br/ConsultarLoteRps", ReplyAction="*")]
        AmericanaWebService.ConsultarLoteRpsResponse ConsultarLoteRps(AmericanaWebService.ConsultarLoteRpsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.nfe.com.br/ConsultarLoteRps", ReplyAction="*")]
        System.Threading.Tasks.Task<AmericanaWebService.ConsultarLoteRpsResponse> ConsultarLoteRpsAsync(AmericanaWebService.ConsultarLoteRpsRequest request);
        
        // CODEGEN: Generating message contract since the wrapper name (ConsultarSituacaoLoteRpsRequest) of message ConsultarSituacaoLoteRpsRequest does not match the default value (ConsultarSituacaoLoteRps)
        [System.ServiceModel.OperationContractAttribute(Action="http://www.nfe.com.br/ConsultarSituacaoLoteRps", ReplyAction="*")]
        AmericanaWebService.ConsultarSituacaoLoteRpsResponse ConsultarSituacaoLoteRps(AmericanaWebService.ConsultarSituacaoLoteRpsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.nfe.com.br/ConsultarSituacaoLoteRps", ReplyAction="*")]
        System.Threading.Tasks.Task<AmericanaWebService.ConsultarSituacaoLoteRpsResponse> ConsultarSituacaoLoteRpsAsync(AmericanaWebService.ConsultarSituacaoLoteRpsRequest request);
        
        // CODEGEN: Generating message contract since the wrapper name (RecepcionarLoteRpsRequest) of message RecepcionarLoteRpsRequest does not match the default value (RecepcionarLoteRps)
        [System.ServiceModel.OperationContractAttribute(Action="http://www.nfe.com.br/RecepcionarLoteRps", ReplyAction="*")]
        AmericanaWebService.RecepcionarLoteRpsResponse RecepcionarLoteRps(AmericanaWebService.RecepcionarLoteRpsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.nfe.com.br/RecepcionarLoteRps", ReplyAction="*")]
        System.Threading.Tasks.Task<AmericanaWebService.RecepcionarLoteRpsResponse> RecepcionarLoteRpsAsync(AmericanaWebService.RecepcionarLoteRpsRequest request);
        
        // CODEGEN: Generating message contract since the wrapper name (CancelarNfseRequest) of message CancelarNfseRequest does not match the default value (CancelarNfse)
        [System.ServiceModel.OperationContractAttribute(Action="http://www.nfe.com.br/CancelarNfse", ReplyAction="*")]
        AmericanaWebService.CancelarNfseResponse CancelarNfse(AmericanaWebService.CancelarNfseRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.nfe.com.br/CancelarNfse", ReplyAction="*")]
        System.Threading.Tasks.Task<AmericanaWebService.CancelarNfseResponse> CancelarNfseAsync(AmericanaWebService.CancelarNfseRequest request);
        
        // CODEGEN: Generating message contract since the wrapper name (GerarNfseRequest) of message GerarNfseRequest does not match the default value (GerarNfse)
        [System.ServiceModel.OperationContractAttribute(Action="http://www.nfe.com.br/GerarNfse", ReplyAction="*")]
        AmericanaWebService.GerarNfseResponse GerarNfse(AmericanaWebService.GerarNfseRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.nfe.com.br/GerarNfse", ReplyAction="*")]
        System.Threading.Tasks.Task<AmericanaWebService.GerarNfseResponse> GerarNfseAsync(AmericanaWebService.GerarNfseRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ConsultarNfseRequest", WrapperNamespace="http://www.nfe.com.br/", IsWrapped=true)]
    public partial class ConsultarNfseRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.nfe.com.br/", Order=0)]
        public string inputXML;
        
        public ConsultarNfseRequest()
        {
        }
        
        public ConsultarNfseRequest(string inputXML)
        {
            this.inputXML = inputXML;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ConsultarNfseResponse", WrapperNamespace="http://www.nfe.com.br/", IsWrapped=true)]
    public partial class ConsultarNfseResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.nfe.com.br/", Order=0)]
        public string outputXML;
        
        public ConsultarNfseResponse()
        {
        }
        
        public ConsultarNfseResponse(string outputXML)
        {
            this.outputXML = outputXML;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ConsultarNfsePorRpsRequest", WrapperNamespace="http://www.nfe.com.br/", IsWrapped=true)]
    public partial class ConsultarNfsePorRpsRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.nfe.com.br/", Order=0)]
        public string inputXML;
        
        public ConsultarNfsePorRpsRequest()
        {
        }
        
        public ConsultarNfsePorRpsRequest(string inputXML)
        {
            this.inputXML = inputXML;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ConsultarNfsePorRpsResponse", WrapperNamespace="http://www.nfe.com.br/", IsWrapped=true)]
    public partial class ConsultarNfsePorRpsResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.nfe.com.br/", Order=0)]
        public string outputXML;
        
        public ConsultarNfsePorRpsResponse()
        {
        }
        
        public ConsultarNfsePorRpsResponse(string outputXML)
        {
            this.outputXML = outputXML;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ConsultarLoteRpsRequest", WrapperNamespace="http://www.nfe.com.br/", IsWrapped=true)]
    public partial class ConsultarLoteRpsRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.nfe.com.br/", Order=0)]
        public string inputXML;
        
        public ConsultarLoteRpsRequest()
        {
        }
        
        public ConsultarLoteRpsRequest(string inputXML)
        {
            this.inputXML = inputXML;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ConsultarLoteRpsResponse", WrapperNamespace="http://www.nfe.com.br/", IsWrapped=true)]
    public partial class ConsultarLoteRpsResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.nfe.com.br/", Order=0)]
        public string outputXML;
        
        public ConsultarLoteRpsResponse()
        {
        }
        
        public ConsultarLoteRpsResponse(string outputXML)
        {
            this.outputXML = outputXML;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ConsultarSituacaoLoteRpsRequest", WrapperNamespace="http://www.nfe.com.br/", IsWrapped=true)]
    public partial class ConsultarSituacaoLoteRpsRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.nfe.com.br/", Order=0)]
        public string inputXML;
        
        public ConsultarSituacaoLoteRpsRequest()
        {
        }
        
        public ConsultarSituacaoLoteRpsRequest(string inputXML)
        {
            this.inputXML = inputXML;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ConsultarSituacaoLoteRpsResponse", WrapperNamespace="http://www.nfe.com.br/", IsWrapped=true)]
    public partial class ConsultarSituacaoLoteRpsResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.nfe.com.br/", Order=0)]
        public string outputXML;
        
        public ConsultarSituacaoLoteRpsResponse()
        {
        }
        
        public ConsultarSituacaoLoteRpsResponse(string outputXML)
        {
            this.outputXML = outputXML;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="RecepcionarLoteRpsRequest", WrapperNamespace="http://www.nfe.com.br/", IsWrapped=true)]
    public partial class RecepcionarLoteRpsRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.nfe.com.br/", Order=0)]
        public string inputXML;
        
        public RecepcionarLoteRpsRequest()
        {
        }
        
        public RecepcionarLoteRpsRequest(string inputXML)
        {
            this.inputXML = inputXML;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="RecepcionarLoteRpsResponse", WrapperNamespace="http://www.nfe.com.br/", IsWrapped=true)]
    public partial class RecepcionarLoteRpsResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.nfe.com.br/", Order=0)]
        public string outputXML;
        
        public RecepcionarLoteRpsResponse()
        {
        }
        
        public RecepcionarLoteRpsResponse(string outputXML)
        {
            this.outputXML = outputXML;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="CancelarNfseRequest", WrapperNamespace="http://www.nfe.com.br/", IsWrapped=true)]
    public partial class CancelarNfseRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.nfe.com.br/", Order=0)]
        public string inputXML;
        
        public CancelarNfseRequest()
        {
        }
        
        public CancelarNfseRequest(string inputXML)
        {
            this.inputXML = inputXML;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="CancelarNfseResponse", WrapperNamespace="http://www.nfe.com.br/", IsWrapped=true)]
    public partial class CancelarNfseResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.nfe.com.br/", Order=0)]
        public string outputXML;
        
        public CancelarNfseResponse()
        {
        }
        
        public CancelarNfseResponse(string outputXML)
        {
            this.outputXML = outputXML;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GerarNfseRequest", WrapperNamespace="http://www.nfe.com.br/", IsWrapped=true)]
    public partial class GerarNfseRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.nfe.com.br/", Order=0)]
        public string inputXML;
        
        public GerarNfseRequest()
        {
        }
        
        public GerarNfseRequest(string inputXML)
        {
            this.inputXML = inputXML;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GerarNfseResponse", WrapperNamespace="http://www.nfe.com.br/", IsWrapped=true)]
    public partial class GerarNfseResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.nfe.com.br/", Order=0)]
        public string outputXML;
        
        public GerarNfseResponse()
        {
        }
        
        public GerarNfseResponse(string outputXML)
        {
            this.outputXML = outputXML;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    public interface NFSESoapChannel : AmericanaWebService.NFSESoap, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    public partial class NFSESoapClient : System.ServiceModel.ClientBase<AmericanaWebService.NFSESoap>, AmericanaWebService.NFSESoap
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public NFSESoapClient() : 
                base(NFSESoapClient.GetDefaultBinding(), NFSESoapClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.NFSESoap.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public NFSESoapClient(EndpointConfiguration endpointConfiguration) : 
                base(NFSESoapClient.GetBindingForEndpoint(endpointConfiguration), NFSESoapClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public NFSESoapClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(NFSESoapClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public NFSESoapClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(NFSESoapClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public NFSESoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        AmericanaWebService.ConsultarNfseResponse AmericanaWebService.NFSESoap.ConsultarNfse(AmericanaWebService.ConsultarNfseRequest request)
        {
            return base.Channel.ConsultarNfse(request);
        }
        
        public string ConsultarNfse(string inputXML)
        {
            AmericanaWebService.ConsultarNfseRequest inValue = new AmericanaWebService.ConsultarNfseRequest();
            inValue.inputXML = inputXML;
            AmericanaWebService.ConsultarNfseResponse retVal = ((AmericanaWebService.NFSESoap)(this)).ConsultarNfse(inValue);
            return retVal.outputXML;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<AmericanaWebService.ConsultarNfseResponse> AmericanaWebService.NFSESoap.ConsultarNfseAsync(AmericanaWebService.ConsultarNfseRequest request)
        {
            return base.Channel.ConsultarNfseAsync(request);
        }
        
        public System.Threading.Tasks.Task<AmericanaWebService.ConsultarNfseResponse> ConsultarNfseAsync(string inputXML)
        {
            AmericanaWebService.ConsultarNfseRequest inValue = new AmericanaWebService.ConsultarNfseRequest();
            inValue.inputXML = inputXML;
            return ((AmericanaWebService.NFSESoap)(this)).ConsultarNfseAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        AmericanaWebService.ConsultarNfsePorRpsResponse AmericanaWebService.NFSESoap.ConsultarNfsePorRps(AmericanaWebService.ConsultarNfsePorRpsRequest request)
        {
            return base.Channel.ConsultarNfsePorRps(request);
        }
        
        public string ConsultarNfsePorRps(string inputXML)
        {
            AmericanaWebService.ConsultarNfsePorRpsRequest inValue = new AmericanaWebService.ConsultarNfsePorRpsRequest();
            inValue.inputXML = inputXML;
            AmericanaWebService.ConsultarNfsePorRpsResponse retVal = ((AmericanaWebService.NFSESoap)(this)).ConsultarNfsePorRps(inValue);
            return retVal.outputXML;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<AmericanaWebService.ConsultarNfsePorRpsResponse> AmericanaWebService.NFSESoap.ConsultarNfsePorRpsAsync(AmericanaWebService.ConsultarNfsePorRpsRequest request)
        {
            return base.Channel.ConsultarNfsePorRpsAsync(request);
        }
        
        public System.Threading.Tasks.Task<AmericanaWebService.ConsultarNfsePorRpsResponse> ConsultarNfsePorRpsAsync(string inputXML)
        {
            AmericanaWebService.ConsultarNfsePorRpsRequest inValue = new AmericanaWebService.ConsultarNfsePorRpsRequest();
            inValue.inputXML = inputXML;
            return ((AmericanaWebService.NFSESoap)(this)).ConsultarNfsePorRpsAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        AmericanaWebService.ConsultarLoteRpsResponse AmericanaWebService.NFSESoap.ConsultarLoteRps(AmericanaWebService.ConsultarLoteRpsRequest request)
        {
            return base.Channel.ConsultarLoteRps(request);
        }
        
        public string ConsultarLoteRps(string inputXML)
        {
            AmericanaWebService.ConsultarLoteRpsRequest inValue = new AmericanaWebService.ConsultarLoteRpsRequest();
            inValue.inputXML = inputXML;
            AmericanaWebService.ConsultarLoteRpsResponse retVal = ((AmericanaWebService.NFSESoap)(this)).ConsultarLoteRps(inValue);
            return retVal.outputXML;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<AmericanaWebService.ConsultarLoteRpsResponse> AmericanaWebService.NFSESoap.ConsultarLoteRpsAsync(AmericanaWebService.ConsultarLoteRpsRequest request)
        {
            return base.Channel.ConsultarLoteRpsAsync(request);
        }
        
        public System.Threading.Tasks.Task<AmericanaWebService.ConsultarLoteRpsResponse> ConsultarLoteRpsAsync(string inputXML)
        {
            AmericanaWebService.ConsultarLoteRpsRequest inValue = new AmericanaWebService.ConsultarLoteRpsRequest();
            inValue.inputXML = inputXML;
            return ((AmericanaWebService.NFSESoap)(this)).ConsultarLoteRpsAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        AmericanaWebService.ConsultarSituacaoLoteRpsResponse AmericanaWebService.NFSESoap.ConsultarSituacaoLoteRps(AmericanaWebService.ConsultarSituacaoLoteRpsRequest request)
        {
            return base.Channel.ConsultarSituacaoLoteRps(request);
        }
        
        public string ConsultarSituacaoLoteRps(string inputXML)
        {
            AmericanaWebService.ConsultarSituacaoLoteRpsRequest inValue = new AmericanaWebService.ConsultarSituacaoLoteRpsRequest();
            inValue.inputXML = inputXML;
            AmericanaWebService.ConsultarSituacaoLoteRpsResponse retVal = ((AmericanaWebService.NFSESoap)(this)).ConsultarSituacaoLoteRps(inValue);
            return retVal.outputXML;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<AmericanaWebService.ConsultarSituacaoLoteRpsResponse> AmericanaWebService.NFSESoap.ConsultarSituacaoLoteRpsAsync(AmericanaWebService.ConsultarSituacaoLoteRpsRequest request)
        {
            return base.Channel.ConsultarSituacaoLoteRpsAsync(request);
        }
        
        public System.Threading.Tasks.Task<AmericanaWebService.ConsultarSituacaoLoteRpsResponse> ConsultarSituacaoLoteRpsAsync(string inputXML)
        {
            AmericanaWebService.ConsultarSituacaoLoteRpsRequest inValue = new AmericanaWebService.ConsultarSituacaoLoteRpsRequest();
            inValue.inputXML = inputXML;
            return ((AmericanaWebService.NFSESoap)(this)).ConsultarSituacaoLoteRpsAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        AmericanaWebService.RecepcionarLoteRpsResponse AmericanaWebService.NFSESoap.RecepcionarLoteRps(AmericanaWebService.RecepcionarLoteRpsRequest request)
        {
            return base.Channel.RecepcionarLoteRps(request);
        }
        
        public string RecepcionarLoteRps(string inputXML)
        {
            AmericanaWebService.RecepcionarLoteRpsRequest inValue = new AmericanaWebService.RecepcionarLoteRpsRequest();
            inValue.inputXML = inputXML;
            AmericanaWebService.RecepcionarLoteRpsResponse retVal = ((AmericanaWebService.NFSESoap)(this)).RecepcionarLoteRps(inValue);
            return retVal.outputXML;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<AmericanaWebService.RecepcionarLoteRpsResponse> AmericanaWebService.NFSESoap.RecepcionarLoteRpsAsync(AmericanaWebService.RecepcionarLoteRpsRequest request)
        {
            return base.Channel.RecepcionarLoteRpsAsync(request);
        }
        
        public System.Threading.Tasks.Task<AmericanaWebService.RecepcionarLoteRpsResponse> RecepcionarLoteRpsAsync(string inputXML)
        {
            AmericanaWebService.RecepcionarLoteRpsRequest inValue = new AmericanaWebService.RecepcionarLoteRpsRequest();
            inValue.inputXML = inputXML;
            return ((AmericanaWebService.NFSESoap)(this)).RecepcionarLoteRpsAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        AmericanaWebService.CancelarNfseResponse AmericanaWebService.NFSESoap.CancelarNfse(AmericanaWebService.CancelarNfseRequest request)
        {
            return base.Channel.CancelarNfse(request);
        }
        
        public string CancelarNfse(string inputXML)
        {
            AmericanaWebService.CancelarNfseRequest inValue = new AmericanaWebService.CancelarNfseRequest();
            inValue.inputXML = inputXML;
            AmericanaWebService.CancelarNfseResponse retVal = ((AmericanaWebService.NFSESoap)(this)).CancelarNfse(inValue);
            return retVal.outputXML;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<AmericanaWebService.CancelarNfseResponse> AmericanaWebService.NFSESoap.CancelarNfseAsync(AmericanaWebService.CancelarNfseRequest request)
        {
            return base.Channel.CancelarNfseAsync(request);
        }
        
        public System.Threading.Tasks.Task<AmericanaWebService.CancelarNfseResponse> CancelarNfseAsync(string inputXML)
        {
            AmericanaWebService.CancelarNfseRequest inValue = new AmericanaWebService.CancelarNfseRequest();
            inValue.inputXML = inputXML;
            return ((AmericanaWebService.NFSESoap)(this)).CancelarNfseAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        AmericanaWebService.GerarNfseResponse AmericanaWebService.NFSESoap.GerarNfse(AmericanaWebService.GerarNfseRequest request)
        {
            return base.Channel.GerarNfse(request);
        }
        
        public string GerarNfse(string inputXML)
        {
            AmericanaWebService.GerarNfseRequest inValue = new AmericanaWebService.GerarNfseRequest();
            inValue.inputXML = inputXML;
            AmericanaWebService.GerarNfseResponse retVal = ((AmericanaWebService.NFSESoap)(this)).GerarNfse(inValue);
            return retVal.outputXML;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<AmericanaWebService.GerarNfseResponse> AmericanaWebService.NFSESoap.GerarNfseAsync(AmericanaWebService.GerarNfseRequest request)
        {
            return base.Channel.GerarNfseAsync(request);
        }
        
        public System.Threading.Tasks.Task<AmericanaWebService.GerarNfseResponse> GerarNfseAsync(string inputXML)
        {
            AmericanaWebService.GerarNfseRequest inValue = new AmericanaWebService.GerarNfseRequest();
            inValue.inputXML = inputXML;
            return ((AmericanaWebService.NFSESoap)(this)).GerarNfseAsync(inValue);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.NFSESoap))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                result.Security.Mode = System.ServiceModel.BasicHttpSecurityMode.Transport;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.NFSESoap))
            {
                return new System.ServiceModel.EndpointAddress("https://nfse.americana.sp.gov.br/nfse/WSNacional/nfse.asmx");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return NFSESoapClient.GetBindingForEndpoint(EndpointConfiguration.NFSESoap);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return NFSESoapClient.GetEndpointAddress(EndpointConfiguration.NFSESoap);
        }
        
        public enum EndpointConfiguration
        {
            
            NFSESoap,
        }
    }
}
