//------------------------------------------------------------------------------
// <auto-generated>
//     Esse código foi gerado por uma ferramenta.
//
//     As alterações no arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SaoPauloWebService
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.prefeitura.sp.gov.br/nfe", ConfigurationName="SaoPauloWebService.LoteNFeSoap")]
    public interface LoteNFeSoap
    {
        
        // CODEGEN: Gerando contrato de mensagem porque o nome do wrapper (EnvioRPSRequest) da mensagem EnvioRPSRequest não corresponde ao valor padrão (EnvioRPS)
        [System.ServiceModel.OperationContractAttribute(Action="http://www.prefeitura.sp.gov.br/nfe/ws/envioRPS", ReplyAction="*")]
        SaoPauloWebService.EnvioRPSResponse EnvioRPS(SaoPauloWebService.EnvioRPSRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.prefeitura.sp.gov.br/nfe/ws/envioRPS", ReplyAction="*")]
        System.Threading.Tasks.Task<SaoPauloWebService.EnvioRPSResponse> EnvioRPSAsync(SaoPauloWebService.EnvioRPSRequest request);
        
        // CODEGEN: Gerando contrato de mensagem porque o nome do wrapper (EnvioLoteRPSRequest) da mensagem EnvioLoteRPSRequest não corresponde ao valor padrão (EnvioLoteRPS)
        [System.ServiceModel.OperationContractAttribute(Action="http://www.prefeitura.sp.gov.br/nfe/ws/envioLoteRPS", ReplyAction="*")]
        SaoPauloWebService.EnvioLoteRPSResponse EnvioLoteRPS(SaoPauloWebService.EnvioLoteRPSRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.prefeitura.sp.gov.br/nfe/ws/envioLoteRPS", ReplyAction="*")]
        System.Threading.Tasks.Task<SaoPauloWebService.EnvioLoteRPSResponse> EnvioLoteRPSAsync(SaoPauloWebService.EnvioLoteRPSRequest request);
        
        // CODEGEN: Gerando contrato de mensagem porque o nome do wrapper (TesteEnvioLoteRPSRequest) da mensagem TesteEnvioLoteRPSRequest não corresponde ao valor padrão (TesteEnvioLoteRPS)
        [System.ServiceModel.OperationContractAttribute(Action="http://www.prefeitura.sp.gov.br/nfe/ws/testeenvio", ReplyAction="*")]
        SaoPauloWebService.TesteEnvioLoteRPSResponse TesteEnvioLoteRPS(SaoPauloWebService.TesteEnvioLoteRPSRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.prefeitura.sp.gov.br/nfe/ws/testeenvio", ReplyAction="*")]
        System.Threading.Tasks.Task<SaoPauloWebService.TesteEnvioLoteRPSResponse> TesteEnvioLoteRPSAsync(SaoPauloWebService.TesteEnvioLoteRPSRequest request);
        
        // CODEGEN: Gerando contrato de mensagem porque o nome do wrapper (CancelamentoNFeRequest) da mensagem CancelamentoNFeRequest não corresponde ao valor padrão (CancelamentoNFe)
        [System.ServiceModel.OperationContractAttribute(Action="http://www.prefeitura.sp.gov.br/nfe/ws/cancelamentoNFe", ReplyAction="*")]
        SaoPauloWebService.CancelamentoNFeResponse CancelamentoNFe(SaoPauloWebService.CancelamentoNFeRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.prefeitura.sp.gov.br/nfe/ws/cancelamentoNFe", ReplyAction="*")]
        System.Threading.Tasks.Task<SaoPauloWebService.CancelamentoNFeResponse> CancelamentoNFeAsync(SaoPauloWebService.CancelamentoNFeRequest request);
        
        // CODEGEN: Gerando contrato de mensagem porque o nome do wrapper (ConsultaNFeRequest) da mensagem ConsultaNFeRequest não corresponde ao valor padrão (ConsultaNFe)
        [System.ServiceModel.OperationContractAttribute(Action="http://www.prefeitura.sp.gov.br/nfe/ws/consultaNFe", ReplyAction="*")]
        SaoPauloWebService.ConsultaNFeResponse ConsultaNFe(SaoPauloWebService.ConsultaNFeRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.prefeitura.sp.gov.br/nfe/ws/consultaNFe", ReplyAction="*")]
        System.Threading.Tasks.Task<SaoPauloWebService.ConsultaNFeResponse> ConsultaNFeAsync(SaoPauloWebService.ConsultaNFeRequest request);
        
        // CODEGEN: Gerando contrato de mensagem porque o nome do wrapper (ConsultaNFeRecebidasRequest) da mensagem ConsultaNFeRecebidasRequest não corresponde ao valor padrão (ConsultaNFeRecebidas)
        [System.ServiceModel.OperationContractAttribute(Action="http://www.prefeitura.sp.gov.br/nfe/ws/consultaNFeRecebidas", ReplyAction="*")]
        SaoPauloWebService.ConsultaNFeRecebidasResponse ConsultaNFeRecebidas(SaoPauloWebService.ConsultaNFeRecebidasRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.prefeitura.sp.gov.br/nfe/ws/consultaNFeRecebidas", ReplyAction="*")]
        System.Threading.Tasks.Task<SaoPauloWebService.ConsultaNFeRecebidasResponse> ConsultaNFeRecebidasAsync(SaoPauloWebService.ConsultaNFeRecebidasRequest request);
        
        // CODEGEN: Gerando contrato de mensagem porque o nome do wrapper (ConsultaNFeEmitidasRequest) da mensagem ConsultaNFeEmitidasRequest não corresponde ao valor padrão (ConsultaNFeEmitidas)
        [System.ServiceModel.OperationContractAttribute(Action="http://www.prefeitura.sp.gov.br/nfe/ws/consultaNFeEmitidas", ReplyAction="*")]
        SaoPauloWebService.ConsultaNFeEmitidasResponse ConsultaNFeEmitidas(SaoPauloWebService.ConsultaNFeEmitidasRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.prefeitura.sp.gov.br/nfe/ws/consultaNFeEmitidas", ReplyAction="*")]
        System.Threading.Tasks.Task<SaoPauloWebService.ConsultaNFeEmitidasResponse> ConsultaNFeEmitidasAsync(SaoPauloWebService.ConsultaNFeEmitidasRequest request);
        
        // CODEGEN: Gerando contrato de mensagem porque o nome do wrapper (ConsultaLoteRequest) da mensagem ConsultaLoteRequest não corresponde ao valor padrão (ConsultaLote)
        [System.ServiceModel.OperationContractAttribute(Action="http://www.prefeitura.sp.gov.br/nfe/ws/consultaLote", ReplyAction="*")]
        SaoPauloWebService.ConsultaLoteResponse ConsultaLote(SaoPauloWebService.ConsultaLoteRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.prefeitura.sp.gov.br/nfe/ws/consultaLote", ReplyAction="*")]
        System.Threading.Tasks.Task<SaoPauloWebService.ConsultaLoteResponse> ConsultaLoteAsync(SaoPauloWebService.ConsultaLoteRequest request);
        
        // CODEGEN: Gerando contrato de mensagem porque o nome do wrapper (ConsultaInformacoesLoteRequest) da mensagem ConsultaInformacoesLoteRequest não corresponde ao valor padrão (ConsultaInformacoesLote)
        [System.ServiceModel.OperationContractAttribute(Action="http://www.prefeitura.sp.gov.br/nfe/ws/consultaInformacoesLote", ReplyAction="*")]
        SaoPauloWebService.ConsultaInformacoesLoteResponse ConsultaInformacoesLote(SaoPauloWebService.ConsultaInformacoesLoteRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.prefeitura.sp.gov.br/nfe/ws/consultaInformacoesLote", ReplyAction="*")]
        System.Threading.Tasks.Task<SaoPauloWebService.ConsultaInformacoesLoteResponse> ConsultaInformacoesLoteAsync(SaoPauloWebService.ConsultaInformacoesLoteRequest request);
        
        // CODEGEN: Gerando contrato de mensagem porque o nome do wrapper (ConsultaCNPJRequest) da mensagem ConsultaCNPJRequest não corresponde ao valor padrão (ConsultaCNPJ)
        [System.ServiceModel.OperationContractAttribute(Action="http://www.prefeitura.sp.gov.br/nfe/ws/consultaCNPJ", ReplyAction="*")]
        SaoPauloWebService.ConsultaCNPJResponse ConsultaCNPJ(SaoPauloWebService.ConsultaCNPJRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.prefeitura.sp.gov.br/nfe/ws/consultaCNPJ", ReplyAction="*")]
        System.Threading.Tasks.Task<SaoPauloWebService.ConsultaCNPJResponse> ConsultaCNPJAsync(SaoPauloWebService.ConsultaCNPJRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="EnvioRPSRequest", WrapperNamespace="http://www.prefeitura.sp.gov.br/nfe", IsWrapped=true)]
    public partial class EnvioRPSRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.prefeitura.sp.gov.br/nfe", Order=0)]
        public int VersaoSchema;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.prefeitura.sp.gov.br/nfe", Order=1)]
        public string MensagemXML;
        
        public EnvioRPSRequest()
        {
        }
        
        public EnvioRPSRequest(int VersaoSchema, string MensagemXML)
        {
            this.VersaoSchema = VersaoSchema;
            this.MensagemXML = MensagemXML;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="EnvioRPSResponse", WrapperNamespace="http://www.prefeitura.sp.gov.br/nfe", IsWrapped=true)]
    public partial class EnvioRPSResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.prefeitura.sp.gov.br/nfe", Order=0)]
        public string RetornoXML;
        
        public EnvioRPSResponse()
        {
        }
        
        public EnvioRPSResponse(string RetornoXML)
        {
            this.RetornoXML = RetornoXML;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="EnvioLoteRPSRequest", WrapperNamespace="http://www.prefeitura.sp.gov.br/nfe", IsWrapped=true)]
    public partial class EnvioLoteRPSRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.prefeitura.sp.gov.br/nfe", Order=0)]
        public int VersaoSchema;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.prefeitura.sp.gov.br/nfe", Order=1)]
        public string MensagemXML;
        
        public EnvioLoteRPSRequest()
        {
        }
        
        public EnvioLoteRPSRequest(int VersaoSchema, string MensagemXML)
        {
            this.VersaoSchema = VersaoSchema;
            this.MensagemXML = MensagemXML;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="EnvioLoteRPSResponse", WrapperNamespace="http://www.prefeitura.sp.gov.br/nfe", IsWrapped=true)]
    public partial class EnvioLoteRPSResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.prefeitura.sp.gov.br/nfe", Order=0)]
        public string RetornoXML;
        
        public EnvioLoteRPSResponse()
        {
        }
        
        public EnvioLoteRPSResponse(string RetornoXML)
        {
            this.RetornoXML = RetornoXML;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="TesteEnvioLoteRPSRequest", WrapperNamespace="http://www.prefeitura.sp.gov.br/nfe", IsWrapped=true)]
    public partial class TesteEnvioLoteRPSRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.prefeitura.sp.gov.br/nfe", Order=0)]
        public int VersaoSchema;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.prefeitura.sp.gov.br/nfe", Order=1)]
        public string MensagemXML;
        
        public TesteEnvioLoteRPSRequest()
        {
        }
        
        public TesteEnvioLoteRPSRequest(int VersaoSchema, string MensagemXML)
        {
            this.VersaoSchema = VersaoSchema;
            this.MensagemXML = MensagemXML;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="TesteEnvioLoteRPSResponse", WrapperNamespace="http://www.prefeitura.sp.gov.br/nfe", IsWrapped=true)]
    public partial class TesteEnvioLoteRPSResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.prefeitura.sp.gov.br/nfe", Order=0)]
        public string RetornoXML;
        
        public TesteEnvioLoteRPSResponse()
        {
        }
        
        public TesteEnvioLoteRPSResponse(string RetornoXML)
        {
            this.RetornoXML = RetornoXML;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="CancelamentoNFeRequest", WrapperNamespace="http://www.prefeitura.sp.gov.br/nfe", IsWrapped=true)]
    public partial class CancelamentoNFeRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.prefeitura.sp.gov.br/nfe", Order=0)]
        public int VersaoSchema;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.prefeitura.sp.gov.br/nfe", Order=1)]
        public string MensagemXML;
        
        public CancelamentoNFeRequest()
        {
        }
        
        public CancelamentoNFeRequest(int VersaoSchema, string MensagemXML)
        {
            this.VersaoSchema = VersaoSchema;
            this.MensagemXML = MensagemXML;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="CancelamentoNFeResponse", WrapperNamespace="http://www.prefeitura.sp.gov.br/nfe", IsWrapped=true)]
    public partial class CancelamentoNFeResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.prefeitura.sp.gov.br/nfe", Order=0)]
        public string RetornoXML;
        
        public CancelamentoNFeResponse()
        {
        }
        
        public CancelamentoNFeResponse(string RetornoXML)
        {
            this.RetornoXML = RetornoXML;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ConsultaNFeRequest", WrapperNamespace="http://www.prefeitura.sp.gov.br/nfe", IsWrapped=true)]
    public partial class ConsultaNFeRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.prefeitura.sp.gov.br/nfe", Order=0)]
        public int VersaoSchema;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.prefeitura.sp.gov.br/nfe", Order=1)]
        public string MensagemXML;
        
        public ConsultaNFeRequest()
        {
        }
        
        public ConsultaNFeRequest(int VersaoSchema, string MensagemXML)
        {
            this.VersaoSchema = VersaoSchema;
            this.MensagemXML = MensagemXML;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ConsultaNFeResponse", WrapperNamespace="http://www.prefeitura.sp.gov.br/nfe", IsWrapped=true)]
    public partial class ConsultaNFeResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.prefeitura.sp.gov.br/nfe", Order=0)]
        public string RetornoXML;
        
        public ConsultaNFeResponse()
        {
        }
        
        public ConsultaNFeResponse(string RetornoXML)
        {
            this.RetornoXML = RetornoXML;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ConsultaNFeRecebidasRequest", WrapperNamespace="http://www.prefeitura.sp.gov.br/nfe", IsWrapped=true)]
    public partial class ConsultaNFeRecebidasRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.prefeitura.sp.gov.br/nfe", Order=0)]
        public int VersaoSchema;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.prefeitura.sp.gov.br/nfe", Order=1)]
        public string MensagemXML;
        
        public ConsultaNFeRecebidasRequest()
        {
        }
        
        public ConsultaNFeRecebidasRequest(int VersaoSchema, string MensagemXML)
        {
            this.VersaoSchema = VersaoSchema;
            this.MensagemXML = MensagemXML;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ConsultaNFeRecebidasResponse", WrapperNamespace="http://www.prefeitura.sp.gov.br/nfe", IsWrapped=true)]
    public partial class ConsultaNFeRecebidasResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.prefeitura.sp.gov.br/nfe", Order=0)]
        public string RetornoXML;
        
        public ConsultaNFeRecebidasResponse()
        {
        }
        
        public ConsultaNFeRecebidasResponse(string RetornoXML)
        {
            this.RetornoXML = RetornoXML;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ConsultaNFeEmitidasRequest", WrapperNamespace="http://www.prefeitura.sp.gov.br/nfe", IsWrapped=true)]
    public partial class ConsultaNFeEmitidasRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.prefeitura.sp.gov.br/nfe", Order=0)]
        public int VersaoSchema;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.prefeitura.sp.gov.br/nfe", Order=1)]
        public string MensagemXML;
        
        public ConsultaNFeEmitidasRequest()
        {
        }
        
        public ConsultaNFeEmitidasRequest(int VersaoSchema, string MensagemXML)
        {
            this.VersaoSchema = VersaoSchema;
            this.MensagemXML = MensagemXML;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ConsultaNFeEmitidasResponse", WrapperNamespace="http://www.prefeitura.sp.gov.br/nfe", IsWrapped=true)]
    public partial class ConsultaNFeEmitidasResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.prefeitura.sp.gov.br/nfe", Order=0)]
        public string RetornoXML;
        
        public ConsultaNFeEmitidasResponse()
        {
        }
        
        public ConsultaNFeEmitidasResponse(string RetornoXML)
        {
            this.RetornoXML = RetornoXML;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ConsultaLoteRequest", WrapperNamespace="http://www.prefeitura.sp.gov.br/nfe", IsWrapped=true)]
    public partial class ConsultaLoteRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.prefeitura.sp.gov.br/nfe", Order=0)]
        public int VersaoSchema;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.prefeitura.sp.gov.br/nfe", Order=1)]
        public string MensagemXML;
        
        public ConsultaLoteRequest()
        {
        }
        
        public ConsultaLoteRequest(int VersaoSchema, string MensagemXML)
        {
            this.VersaoSchema = VersaoSchema;
            this.MensagemXML = MensagemXML;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ConsultaLoteResponse", WrapperNamespace="http://www.prefeitura.sp.gov.br/nfe", IsWrapped=true)]
    public partial class ConsultaLoteResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.prefeitura.sp.gov.br/nfe", Order=0)]
        public string RetornoXML;
        
        public ConsultaLoteResponse()
        {
        }
        
        public ConsultaLoteResponse(string RetornoXML)
        {
            this.RetornoXML = RetornoXML;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ConsultaInformacoesLoteRequest", WrapperNamespace="http://www.prefeitura.sp.gov.br/nfe", IsWrapped=true)]
    public partial class ConsultaInformacoesLoteRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.prefeitura.sp.gov.br/nfe", Order=0)]
        public int VersaoSchema;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.prefeitura.sp.gov.br/nfe", Order=1)]
        public string MensagemXML;
        
        public ConsultaInformacoesLoteRequest()
        {
        }
        
        public ConsultaInformacoesLoteRequest(int VersaoSchema, string MensagemXML)
        {
            this.VersaoSchema = VersaoSchema;
            this.MensagemXML = MensagemXML;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ConsultaInformacoesLoteResponse", WrapperNamespace="http://www.prefeitura.sp.gov.br/nfe", IsWrapped=true)]
    public partial class ConsultaInformacoesLoteResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.prefeitura.sp.gov.br/nfe", Order=0)]
        public string RetornoXML;
        
        public ConsultaInformacoesLoteResponse()
        {
        }
        
        public ConsultaInformacoesLoteResponse(string RetornoXML)
        {
            this.RetornoXML = RetornoXML;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ConsultaCNPJRequest", WrapperNamespace="http://www.prefeitura.sp.gov.br/nfe", IsWrapped=true)]
    public partial class ConsultaCNPJRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.prefeitura.sp.gov.br/nfe", Order=0)]
        public int VersaoSchema;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.prefeitura.sp.gov.br/nfe", Order=1)]
        public string MensagemXML;
        
        public ConsultaCNPJRequest()
        {
        }
        
        public ConsultaCNPJRequest(int VersaoSchema, string MensagemXML)
        {
            this.VersaoSchema = VersaoSchema;
            this.MensagemXML = MensagemXML;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ConsultaCNPJResponse", WrapperNamespace="http://www.prefeitura.sp.gov.br/nfe", IsWrapped=true)]
    public partial class ConsultaCNPJResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.prefeitura.sp.gov.br/nfe", Order=0)]
        public string RetornoXML;
        
        public ConsultaCNPJResponse()
        {
        }
        
        public ConsultaCNPJResponse(string RetornoXML)
        {
            this.RetornoXML = RetornoXML;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    public interface LoteNFeSoapChannel : SaoPauloWebService.LoteNFeSoap, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    public partial class LoteNFeSoapClient : System.ServiceModel.ClientBase<SaoPauloWebService.LoteNFeSoap>, SaoPauloWebService.LoteNFeSoap
    {
        
        /// <summary>
        /// Implemente este método parcial para configurar o ponto de extremidade de serviço.
        /// </summary>
        /// <param name="serviceEndpoint">O ponto de extremidade a ser configurado</param>
        /// <param name="clientCredentials">As credenciais do cliente</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public LoteNFeSoapClient(EndpointConfiguration endpointConfiguration) : 
                base(LoteNFeSoapClient.GetBindingForEndpoint(endpointConfiguration), LoteNFeSoapClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public LoteNFeSoapClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(LoteNFeSoapClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public LoteNFeSoapClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(LoteNFeSoapClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public LoteNFeSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SaoPauloWebService.EnvioRPSResponse SaoPauloWebService.LoteNFeSoap.EnvioRPS(SaoPauloWebService.EnvioRPSRequest request)
        {
            return base.Channel.EnvioRPS(request);
        }
        
        public string EnvioRPS(int VersaoSchema, string MensagemXML)
        {
            SaoPauloWebService.EnvioRPSRequest inValue = new SaoPauloWebService.EnvioRPSRequest();
            inValue.VersaoSchema = VersaoSchema;
            inValue.MensagemXML = MensagemXML;
            SaoPauloWebService.EnvioRPSResponse retVal = ((SaoPauloWebService.LoteNFeSoap)(this)).EnvioRPS(inValue);
            return retVal.RetornoXML;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SaoPauloWebService.EnvioRPSResponse> SaoPauloWebService.LoteNFeSoap.EnvioRPSAsync(SaoPauloWebService.EnvioRPSRequest request)
        {
            return base.Channel.EnvioRPSAsync(request);
        }
        
        public System.Threading.Tasks.Task<SaoPauloWebService.EnvioRPSResponse> EnvioRPSAsync(int VersaoSchema, string MensagemXML)
        {
            SaoPauloWebService.EnvioRPSRequest inValue = new SaoPauloWebService.EnvioRPSRequest();
            inValue.VersaoSchema = VersaoSchema;
            inValue.MensagemXML = MensagemXML;
            return ((SaoPauloWebService.LoteNFeSoap)(this)).EnvioRPSAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SaoPauloWebService.EnvioLoteRPSResponse SaoPauloWebService.LoteNFeSoap.EnvioLoteRPS(SaoPauloWebService.EnvioLoteRPSRequest request)
        {
            return base.Channel.EnvioLoteRPS(request);
        }
        
        public string EnvioLoteRPS(int VersaoSchema, string MensagemXML)
        {
            SaoPauloWebService.EnvioLoteRPSRequest inValue = new SaoPauloWebService.EnvioLoteRPSRequest();
            inValue.VersaoSchema = VersaoSchema;
            inValue.MensagemXML = MensagemXML;
            SaoPauloWebService.EnvioLoteRPSResponse retVal = ((SaoPauloWebService.LoteNFeSoap)(this)).EnvioLoteRPS(inValue);
            return retVal.RetornoXML;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SaoPauloWebService.EnvioLoteRPSResponse> SaoPauloWebService.LoteNFeSoap.EnvioLoteRPSAsync(SaoPauloWebService.EnvioLoteRPSRequest request)
        {
            return base.Channel.EnvioLoteRPSAsync(request);
        }
        
        public System.Threading.Tasks.Task<SaoPauloWebService.EnvioLoteRPSResponse> EnvioLoteRPSAsync(int VersaoSchema, string MensagemXML)
        {
            SaoPauloWebService.EnvioLoteRPSRequest inValue = new SaoPauloWebService.EnvioLoteRPSRequest();
            inValue.VersaoSchema = VersaoSchema;
            inValue.MensagemXML = MensagemXML;
            return ((SaoPauloWebService.LoteNFeSoap)(this)).EnvioLoteRPSAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SaoPauloWebService.TesteEnvioLoteRPSResponse SaoPauloWebService.LoteNFeSoap.TesteEnvioLoteRPS(SaoPauloWebService.TesteEnvioLoteRPSRequest request)
        {
            return base.Channel.TesteEnvioLoteRPS(request);
        }
        
        public string TesteEnvioLoteRPS(int VersaoSchema, string MensagemXML)
        {
            SaoPauloWebService.TesteEnvioLoteRPSRequest inValue = new SaoPauloWebService.TesteEnvioLoteRPSRequest();
            inValue.VersaoSchema = VersaoSchema;
            inValue.MensagemXML = MensagemXML;
            SaoPauloWebService.TesteEnvioLoteRPSResponse retVal = ((SaoPauloWebService.LoteNFeSoap)(this)).TesteEnvioLoteRPS(inValue);
            return retVal.RetornoXML;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SaoPauloWebService.TesteEnvioLoteRPSResponse> SaoPauloWebService.LoteNFeSoap.TesteEnvioLoteRPSAsync(SaoPauloWebService.TesteEnvioLoteRPSRequest request)
        {
            return base.Channel.TesteEnvioLoteRPSAsync(request);
        }
        
        public System.Threading.Tasks.Task<SaoPauloWebService.TesteEnvioLoteRPSResponse> TesteEnvioLoteRPSAsync(int VersaoSchema, string MensagemXML)
        {
            SaoPauloWebService.TesteEnvioLoteRPSRequest inValue = new SaoPauloWebService.TesteEnvioLoteRPSRequest();
            inValue.VersaoSchema = VersaoSchema;
            inValue.MensagemXML = MensagemXML;
            return ((SaoPauloWebService.LoteNFeSoap)(this)).TesteEnvioLoteRPSAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SaoPauloWebService.CancelamentoNFeResponse SaoPauloWebService.LoteNFeSoap.CancelamentoNFe(SaoPauloWebService.CancelamentoNFeRequest request)
        {
            return base.Channel.CancelamentoNFe(request);
        }
        
        public string CancelamentoNFe(int VersaoSchema, string MensagemXML)
        {
            SaoPauloWebService.CancelamentoNFeRequest inValue = new SaoPauloWebService.CancelamentoNFeRequest();
            inValue.VersaoSchema = VersaoSchema;
            inValue.MensagemXML = MensagemXML;
            SaoPauloWebService.CancelamentoNFeResponse retVal = ((SaoPauloWebService.LoteNFeSoap)(this)).CancelamentoNFe(inValue);
            return retVal.RetornoXML;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SaoPauloWebService.CancelamentoNFeResponse> SaoPauloWebService.LoteNFeSoap.CancelamentoNFeAsync(SaoPauloWebService.CancelamentoNFeRequest request)
        {
            return base.Channel.CancelamentoNFeAsync(request);
        }
        
        public System.Threading.Tasks.Task<SaoPauloWebService.CancelamentoNFeResponse> CancelamentoNFeAsync(int VersaoSchema, string MensagemXML)
        {
            SaoPauloWebService.CancelamentoNFeRequest inValue = new SaoPauloWebService.CancelamentoNFeRequest();
            inValue.VersaoSchema = VersaoSchema;
            inValue.MensagemXML = MensagemXML;
            return ((SaoPauloWebService.LoteNFeSoap)(this)).CancelamentoNFeAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SaoPauloWebService.ConsultaNFeResponse SaoPauloWebService.LoteNFeSoap.ConsultaNFe(SaoPauloWebService.ConsultaNFeRequest request)
        {
            return base.Channel.ConsultaNFe(request);
        }
        
        public string ConsultaNFe(int VersaoSchema, string MensagemXML)
        {
            SaoPauloWebService.ConsultaNFeRequest inValue = new SaoPauloWebService.ConsultaNFeRequest();
            inValue.VersaoSchema = VersaoSchema;
            inValue.MensagemXML = MensagemXML;
            SaoPauloWebService.ConsultaNFeResponse retVal = ((SaoPauloWebService.LoteNFeSoap)(this)).ConsultaNFe(inValue);
            return retVal.RetornoXML;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SaoPauloWebService.ConsultaNFeResponse> SaoPauloWebService.LoteNFeSoap.ConsultaNFeAsync(SaoPauloWebService.ConsultaNFeRequest request)
        {
            return base.Channel.ConsultaNFeAsync(request);
        }
        
        public System.Threading.Tasks.Task<SaoPauloWebService.ConsultaNFeResponse> ConsultaNFeAsync(int VersaoSchema, string MensagemXML)
        {
            SaoPauloWebService.ConsultaNFeRequest inValue = new SaoPauloWebService.ConsultaNFeRequest();
            inValue.VersaoSchema = VersaoSchema;
            inValue.MensagemXML = MensagemXML;
            return ((SaoPauloWebService.LoteNFeSoap)(this)).ConsultaNFeAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SaoPauloWebService.ConsultaNFeRecebidasResponse SaoPauloWebService.LoteNFeSoap.ConsultaNFeRecebidas(SaoPauloWebService.ConsultaNFeRecebidasRequest request)
        {
            return base.Channel.ConsultaNFeRecebidas(request);
        }
        
        public string ConsultaNFeRecebidas(int VersaoSchema, string MensagemXML)
        {
            SaoPauloWebService.ConsultaNFeRecebidasRequest inValue = new SaoPauloWebService.ConsultaNFeRecebidasRequest();
            inValue.VersaoSchema = VersaoSchema;
            inValue.MensagemXML = MensagemXML;
            SaoPauloWebService.ConsultaNFeRecebidasResponse retVal = ((SaoPauloWebService.LoteNFeSoap)(this)).ConsultaNFeRecebidas(inValue);
            return retVal.RetornoXML;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SaoPauloWebService.ConsultaNFeRecebidasResponse> SaoPauloWebService.LoteNFeSoap.ConsultaNFeRecebidasAsync(SaoPauloWebService.ConsultaNFeRecebidasRequest request)
        {
            return base.Channel.ConsultaNFeRecebidasAsync(request);
        }
        
        public System.Threading.Tasks.Task<SaoPauloWebService.ConsultaNFeRecebidasResponse> ConsultaNFeRecebidasAsync(int VersaoSchema, string MensagemXML)
        {
            SaoPauloWebService.ConsultaNFeRecebidasRequest inValue = new SaoPauloWebService.ConsultaNFeRecebidasRequest();
            inValue.VersaoSchema = VersaoSchema;
            inValue.MensagemXML = MensagemXML;
            return ((SaoPauloWebService.LoteNFeSoap)(this)).ConsultaNFeRecebidasAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SaoPauloWebService.ConsultaNFeEmitidasResponse SaoPauloWebService.LoteNFeSoap.ConsultaNFeEmitidas(SaoPauloWebService.ConsultaNFeEmitidasRequest request)
        {
            return base.Channel.ConsultaNFeEmitidas(request);
        }
        
        public string ConsultaNFeEmitidas(int VersaoSchema, string MensagemXML)
        {
            SaoPauloWebService.ConsultaNFeEmitidasRequest inValue = new SaoPauloWebService.ConsultaNFeEmitidasRequest();
            inValue.VersaoSchema = VersaoSchema;
            inValue.MensagemXML = MensagemXML;
            SaoPauloWebService.ConsultaNFeEmitidasResponse retVal = ((SaoPauloWebService.LoteNFeSoap)(this)).ConsultaNFeEmitidas(inValue);
            return retVal.RetornoXML;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SaoPauloWebService.ConsultaNFeEmitidasResponse> SaoPauloWebService.LoteNFeSoap.ConsultaNFeEmitidasAsync(SaoPauloWebService.ConsultaNFeEmitidasRequest request)
        {
            return base.Channel.ConsultaNFeEmitidasAsync(request);
        }
        
        public System.Threading.Tasks.Task<SaoPauloWebService.ConsultaNFeEmitidasResponse> ConsultaNFeEmitidasAsync(int VersaoSchema, string MensagemXML)
        {
            SaoPauloWebService.ConsultaNFeEmitidasRequest inValue = new SaoPauloWebService.ConsultaNFeEmitidasRequest();
            inValue.VersaoSchema = VersaoSchema;
            inValue.MensagemXML = MensagemXML;
            return ((SaoPauloWebService.LoteNFeSoap)(this)).ConsultaNFeEmitidasAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SaoPauloWebService.ConsultaLoteResponse SaoPauloWebService.LoteNFeSoap.ConsultaLote(SaoPauloWebService.ConsultaLoteRequest request)
        {
            return base.Channel.ConsultaLote(request);
        }
        
        public string ConsultaLote(int VersaoSchema, string MensagemXML)
        {
            SaoPauloWebService.ConsultaLoteRequest inValue = new SaoPauloWebService.ConsultaLoteRequest();
            inValue.VersaoSchema = VersaoSchema;
            inValue.MensagemXML = MensagemXML;
            SaoPauloWebService.ConsultaLoteResponse retVal = ((SaoPauloWebService.LoteNFeSoap)(this)).ConsultaLote(inValue);
            return retVal.RetornoXML;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SaoPauloWebService.ConsultaLoteResponse> SaoPauloWebService.LoteNFeSoap.ConsultaLoteAsync(SaoPauloWebService.ConsultaLoteRequest request)
        {
            return base.Channel.ConsultaLoteAsync(request);
        }
        
        public System.Threading.Tasks.Task<SaoPauloWebService.ConsultaLoteResponse> ConsultaLoteAsync(int VersaoSchema, string MensagemXML)
        {
            SaoPauloWebService.ConsultaLoteRequest inValue = new SaoPauloWebService.ConsultaLoteRequest();
            inValue.VersaoSchema = VersaoSchema;
            inValue.MensagemXML = MensagemXML;
            return ((SaoPauloWebService.LoteNFeSoap)(this)).ConsultaLoteAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SaoPauloWebService.ConsultaInformacoesLoteResponse SaoPauloWebService.LoteNFeSoap.ConsultaInformacoesLote(SaoPauloWebService.ConsultaInformacoesLoteRequest request)
        {
            return base.Channel.ConsultaInformacoesLote(request);
        }
        
        public string ConsultaInformacoesLote(int VersaoSchema, string MensagemXML)
        {
            SaoPauloWebService.ConsultaInformacoesLoteRequest inValue = new SaoPauloWebService.ConsultaInformacoesLoteRequest();
            inValue.VersaoSchema = VersaoSchema;
            inValue.MensagemXML = MensagemXML;
            SaoPauloWebService.ConsultaInformacoesLoteResponse retVal = ((SaoPauloWebService.LoteNFeSoap)(this)).ConsultaInformacoesLote(inValue);
            return retVal.RetornoXML;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SaoPauloWebService.ConsultaInformacoesLoteResponse> SaoPauloWebService.LoteNFeSoap.ConsultaInformacoesLoteAsync(SaoPauloWebService.ConsultaInformacoesLoteRequest request)
        {
            return base.Channel.ConsultaInformacoesLoteAsync(request);
        }
        
        public System.Threading.Tasks.Task<SaoPauloWebService.ConsultaInformacoesLoteResponse> ConsultaInformacoesLoteAsync(int VersaoSchema, string MensagemXML)
        {
            SaoPauloWebService.ConsultaInformacoesLoteRequest inValue = new SaoPauloWebService.ConsultaInformacoesLoteRequest();
            inValue.VersaoSchema = VersaoSchema;
            inValue.MensagemXML = MensagemXML;
            return ((SaoPauloWebService.LoteNFeSoap)(this)).ConsultaInformacoesLoteAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SaoPauloWebService.ConsultaCNPJResponse SaoPauloWebService.LoteNFeSoap.ConsultaCNPJ(SaoPauloWebService.ConsultaCNPJRequest request)
        {
            return base.Channel.ConsultaCNPJ(request);
        }
        
        public string ConsultaCNPJ(int VersaoSchema, string MensagemXML)
        {
            SaoPauloWebService.ConsultaCNPJRequest inValue = new SaoPauloWebService.ConsultaCNPJRequest();
            inValue.VersaoSchema = VersaoSchema;
            inValue.MensagemXML = MensagemXML;
            SaoPauloWebService.ConsultaCNPJResponse retVal = ((SaoPauloWebService.LoteNFeSoap)(this)).ConsultaCNPJ(inValue);
            return retVal.RetornoXML;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SaoPauloWebService.ConsultaCNPJResponse> SaoPauloWebService.LoteNFeSoap.ConsultaCNPJAsync(SaoPauloWebService.ConsultaCNPJRequest request)
        {
            return base.Channel.ConsultaCNPJAsync(request);
        }
        
        public System.Threading.Tasks.Task<SaoPauloWebService.ConsultaCNPJResponse> ConsultaCNPJAsync(int VersaoSchema, string MensagemXML)
        {
            SaoPauloWebService.ConsultaCNPJRequest inValue = new SaoPauloWebService.ConsultaCNPJRequest();
            inValue.VersaoSchema = VersaoSchema;
            inValue.MensagemXML = MensagemXML;
            return ((SaoPauloWebService.LoteNFeSoap)(this)).ConsultaCNPJAsync(inValue);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.LoteNFeSoap))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                result.Security.Mode = System.ServiceModel.BasicHttpSecurityMode.Transport;
                
                return result;
            }
            if ((endpointConfiguration == EndpointConfiguration.LoteNFeSoap12))
            {
                System.ServiceModel.Channels.CustomBinding result = new System.ServiceModel.Channels.CustomBinding();
                System.ServiceModel.Channels.TextMessageEncodingBindingElement textBindingElement = new System.ServiceModel.Channels.TextMessageEncodingBindingElement();
                textBindingElement.MessageVersion = System.ServiceModel.Channels.MessageVersion.CreateVersion(System.ServiceModel.EnvelopeVersion.Soap12, System.ServiceModel.Channels.AddressingVersion.None);
                result.Elements.Add(textBindingElement);
                System.ServiceModel.Channels.HttpsTransportBindingElement httpsBindingElement = new System.ServiceModel.Channels.HttpsTransportBindingElement();
                httpsBindingElement.AllowCookies = true;
                httpsBindingElement.MaxBufferSize = int.MaxValue;
                httpsBindingElement.MaxReceivedMessageSize = int.MaxValue;
                httpsBindingElement.RequireClientCertificate = true;
                httpsBindingElement.AuthenticationScheme = System.Net.AuthenticationSchemes.Anonymous;
                result.Elements.Add(httpsBindingElement);
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Não foi possível encontrar o ponto de extremidade com o nome \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.LoteNFeSoap))
            {
                return new System.ServiceModel.EndpointAddress("https://nfe.prefeitura.sp.gov.br/ws/lotenfe.asmx");
            }
            if ((endpointConfiguration == EndpointConfiguration.LoteNFeSoap12))
            {
                return new System.ServiceModel.EndpointAddress("https://nfe.prefeitura.sp.gov.br/ws/lotenfe.asmx");
            }
            throw new System.InvalidOperationException(string.Format("Não foi possível encontrar o ponto de extremidade com o nome \'{0}\'.", endpointConfiguration));
        }
        
        public enum EndpointConfiguration
        {
            
            LoteNFeSoap,
            
            LoteNFeSoap12,
        }
    }
}
